In [80]:
import pandas as pd

DATA_PATH = r"D:\Downloads\archive\twcs\twcs.csv"

df_sample = pd.read_csv(
    DATA_PATH,
    nrows=1000
)

print("Rows:", df_sample.shape[0])
print("Columns:", df_sample.shape[1])
print("\nColumn names:")
print(df_sample.columns.tolist())

Rows: 1000
Columns: 7

Column names:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [81]:
pd.set_option("display.max_colwidth", 200)

df_sample.head(10)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messages and no one is responding as usual,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0
5,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,"@115712 Can you please send us a private message, so that I can gain further details about your account?","5,7",8.0
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN
7,11,sprintcare,False,Tue Oct 31 22:10:35 +0000 2017,"@115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC",NaN,12.0
8,12,115713,True,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯,"11,13,14",15.0
9,15,sprintcare,False,Tue Oct 31 20:03:31 +0000 2017,"@115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further assist you. -AA",12,16.0

In [82]:
df_sample["inbound"].value_counts()

inbound
True     539
False    461
Name: count, dtype: int64

In [83]:
df_sample[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ]
].head(20)

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.,2,3.0
1,2,115712,True,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,@sprintcare I have sent several private messages and no one is responding as usual,1,4.0
3,4,sprintcare,False,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.,3,5.0
4,5,115712,True,@sprintcare I did.,4,6.0
5,6,sprintcare,False,"@115712 Can you please send us a private message, so that I can gain further details about your account?","5,7",8.0
6,8,115712,True,@sprintcare is the worst customer service,"9,6,10",NaN
7,11,sprintcare,False,"@115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC",NaN,12.0
8,12,115713,True,@sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯,"11,13,14",15.0
9,15,sprintcare,False,"@115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further assist you. -AA",12,16.0
10,16,115713,True,@sprintcare Since I signed up with you....Since day 1,15,17.0
11,17,sprintcare,False,"@115713 H there! We'd definitely like to work with you on this, how long have you been experiencing this issue? -AA",16,18.0
12,18,115713,True,"@115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.",17,NaN
13,19,sprintcare,False,@115715 Please send me a private message so that I can send you the link to access your account. -FR,NaN,20.0
14,20,115715,True,"@115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK",19,NaN
15,21,Ask_Spectrum,False,@115716 What information is incorrect? ^JK,"22,23",24.0
16,22,115716,True,@Ask_Spectrum Would you like me to email you a copy of one since Spectrum is not updating your training?,25,21.0
17,25,Ask_Spectrum,False,"@115716 Our department is part of the corporate office. If you're particular area has gone to this format, we were unawa... https://t.co/P7XCmTzPQj",26,22.0
18,26,115716,True,@Ask_Spectrum I received this from your corporate office would you like a copy?,27,25.0
19,27,Ask_Spectrum,False,@115716 No thank you. ^JK,NaN,26.0

In [84]:
df_sample.isnull().sum()

tweet_id                     0
author_id                    0
inbound                      0
created_at                   0
text                         0
response_tweet_id          321
in_response_to_tweet_id    253
dtype: int64

In [85]:
for i, row in df_sample.head(10).iterrows():
    print("Tweet ID:", row["tweet_id"])
    print("Author:", row["author_id"])
    print("Inbound:", row["inbound"])
    print("Text:", row["text"])
    print("-" * 80)

Tweet ID: 1
Author: sprintcare
Inbound: False
Text: @115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.
--------------------------------------------------------------------------------
Tweet ID: 2
Author: 115712
Inbound: True
Text: @sprintcare and how do you propose we do that
--------------------------------------------------------------------------------
Tweet ID: 3
Author: 115712
Inbound: True
Text: @sprintcare I have sent several private messages and no one is responding as usual
--------------------------------------------------------------------------------
Tweet ID: 4
Author: sprintcare
Inbound: False
Text: @115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.
--------------------------------------------------------------------------------
Tweet ID: 5
Author: 115712
Inbound: True
Text: @sprintcare I did.
--------------------------------------------------------------------------------
Tweet ID: 6
Author: sprintcare
Inbound: False
Text: @115712 Can you please send us a private message, so that I can gain further details about your account?
--------------------------------------------------------------------------------
Tweet ID: 8
Author: 115712
Inbound: True
Text: @sprintcare is the worst customer service
--------------------------------------------------------------------------------
Tweet ID: 11
Author: sprintcare
Inbound: False
Text: @115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC
--------------------------------------------------------------------------------
Tweet ID: 12
Author: 115713
Inbound: True
Text: @sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯
--------------------------------------------------------------------------------
Tweet ID: 15
Author: sprintcare
Inbound: False
Text: @115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further assist you. -AA
--------------------------------------------------------------------------------

In [86]:
from collections import Counter
import pandas as pd

brand_counts = Counter()

for chunk in pd.read_csv(
    DATA_PATH,
    usecols=["author_id", "inbound"],
    chunksize=100_000
):
    # Only brand/company tweets
    brand_tweets = chunk[chunk["inbound"] == False]

    # Count tweets by brand account
    brand_counts.update(brand_tweets["author_id"].astype(str))

print("Number of unique brand accounts:", len(brand_counts))

print("\nTop 30 brand accounts:")
for brand, count in brand_counts.most_common(30):
    print(f"{brand:30} {count}")

Number of unique brand accounts: 108

Top 30 brand accounts:
AmazonHelp                     169840
AppleSupport                   106860
Uber_Support                   56270
SpotifyCares                   43265
Delta                          42253
Tesco                          38573
AmericanAir                    36764
TMobileHelp                    34317
comcastcares                   33031
British_Airways                29361
SouthwestAir                   28977
VirginTrains                   27817
Ask_Spectrum                   25860
XboxSupport                    24557
sprintcare                     22381
hulu_support                   21872
sainsburys                     19466
GWRHelp                        19364
AskPlayStation                 19098
ChipotleTweets                 18749
VerizonSupport                 17966
UPSHelp                        17817
ATVIAssist                     17650
O2                             16212
Safaricom_Care                 16077
idea_cares                     15724
AskTarget                      13218
AirAsiaSupport                 12829
BofA_Help                      12683
SW_Help                        12231

In [87]:
import pandas as pd

candidate_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Uber_Support",
    "SpotifyCares",
    "Delta",
    "Tesco",
    "AmericanAir",
    "TMobileHelp"
]

brand_stats = {
    brand: {
        "total_tweets": 0,
        "customer_tweets": 0,
        "brand_tweets": 0,
        "unique_customers": set()
    }
    for brand in candidate_brands
}

for chunk in pd.read_csv(
    DATA_PATH,
    usecols=["author_id", "inbound"],
    chunksize=100_000
):

    # Customer tweets
    customer_rows = chunk[chunk["inbound"] == True]

    # Brand tweets
    brand_rows = chunk[
        (chunk["inbound"] == False) &
        (chunk["author_id"].isin(candidate_brands))
    ]

    for brand in candidate_brands:
        brand_rows_for_brand = brand_rows[
            brand_rows["author_id"] == brand
        ]

        brand_count = len(brand_rows_for_brand)

        brand_stats[brand]["brand_tweets"] += brand_count

    # Count customer tweets
    # We cannot directly associate all customers with a brand yet,
    # so this is intentionally left for the next step.

print("Brand statistics:")
for brand in candidate_brands:
    print(
        brand,
        "→",
        brand_stats[brand]["brand_tweets"],
        "brand tweets"
    )

Brand statistics:
AmazonHelp → 169840 brand tweets
AppleSupport → 106860 brand tweets
Uber_Support → 56270 brand tweets
SpotifyCares → 43265 brand tweets
Delta → 42253 brand tweets
Tesco → 38573 brand tweets
AmericanAir → 36764 brand tweets
TMobileHelp → 34317 brand tweets

In [88]:
amazon_tweet_ids = set()

for chunk in pd.read_csv(
    DATA_PATH,
    usecols=["tweet_id", "author_id"],
    chunksize=100_000
):
    amazon_ids = chunk.loc[
        chunk["author_id"] == "AmazonHelp",
        "tweet_id"
    ]

    amazon_tweet_ids.update(
        amazon_ids.astype(str)
    )

print("AmazonHelp tweet IDs:", len(amazon_tweet_ids))

AmazonHelp tweet IDs: 169840

In [89]:
amazon_conversation_rows = []

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=100_000
):

    chunk["tweet_id"] = chunk["tweet_id"].astype(str)

    # AmazonHelp's own tweets
    is_amazon = chunk["author_id"] == "AmazonHelp"

    # Customer tweets replying directly to AmazonHelp
    replies_to_amazon = (
        chunk["in_response_to_tweet_id"]
        .astype("Int64")
        .astype(str)
        .isin(amazon_tweet_ids)
    )

    selected = chunk[
        is_amazon | replies_to_amazon
    ]

    amazon_conversation_rows.append(selected)

amazon_df = pd.concat(
    amazon_conversation_rows,
    ignore_index=True
)

print("Rows:", len(amazon_df))

Rows: 270344

In [90]:
amazon_examples = []

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=100_000
):
    matches = chunk[
        chunk["author_id"] == "AmazonHelp"
    ]

    if len(matches) > 0:
        amazon_examples.append(matches)

    if sum(len(x) for x in amazon_examples) >= 20:
        break

amazon_examples = pd.concat(
    amazon_examples,
    ignore_index=True
).head(20)

amazon_examples[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "in_response_to_tweet_id",
        "response_tweet_id"
    ]
]

,tweet_id,author_id,inbound,text,in_response_to_tweet_id,response_tweet_id
0,269,AmazonHelp,False,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET,272.0,"270,271"
1,273,AmazonHelp,False,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET,271.0,274
2,275,AmazonHelp,False,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET,274.0,NaN
3,324,AmazonHelp,False,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET,325.0,NaN
4,615,AmazonHelp,False,"@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN",617.0,616
5,618,AmazonHelp,False,@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG,616.0,619
6,620,AmazonHelp,False,"@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH",621.0,NaN
7,622,AmazonHelp,False,"@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS",624.0,623
8,625,AmazonHelp,False,@115824 Wir haben zu danken. Schönen Abend noch. ^JS,623.0,NaN
9,626,AmazonHelp,False,@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ,628.0,627
10,629,AmazonHelp,False,@115827 Thanks for your patience. ^KM,627.0,NaN
11,631,AmazonHelp,False,@115829 I'm sorry your order arrived in this condition! Please reach out to us for available options: https://t.co/JzP7hlA23B ^DG,632.0,NaN
12,633,AmazonHelp,False,@115831 I'm sorry for the wait. Please reach out to us so we can take a closer look at this delivery: https://t.co/JzP7hlA23B ^SH,634.0,NaN
13,635,AmazonHelp,False,@115832 Alexa says both styles are working for you! My vote goes to the Flamingo look! ^SE,636.0,NaN
14,637,AmazonHelp,False,@115834 Were you able to reach us at the link DW provided? ^TR,638.0,NaN
15,639,AmazonHelp,False,"@115834 The Echo Show is supported, please reach us for some live troubleshooting at your convenience: https://t.co/hApLpMlfHN ^DW",640.0,638
16,642,AmazonHelp,False,"@115834 Oh no, I'm sorry for the issues! For troubleshooting, please check out our Echo Help pages here: https://t.co/a31c4ynHES ^SG",643.0,641
17,644,AmazonHelp,False,@115835 I'm so sorry you didn't receive your parcel! We'd like a chance to look into this with you here: https://t.co/JzP7hlA23B ^SY,646.0,645
18,647,AmazonHelp,False,@115835 You can also request a call back here Martin https://t.co/zH8UlhTGcc ^KM,645.0,NaN
19,648,AmazonHelp,False,@115836 Thanks for bringing this to our attention! Please also leave packing feedback here: https://t.co/PMiShxgPvp so we may improve.^KL,649.0,NaN

In [91]:
conversation_ids = [615, 616, 617]

conversation = []

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=100_000
):
    matches = chunk[
        chunk["tweet_id"].isin(conversation_ids)
    ]

    if len(matches) > 0:
        conversation.append(matches)

conversation = pd.concat(
    conversation,
    ignore_index=True
)

conversation = conversation.sort_values("tweet_id")

conversation[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ]
]

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,615,AmazonHelp,False,Tue Oct 31 22:29:00 +0000 2017,"@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN",616,617.0
1,616,115820,True,Tue Oct 31 23:22:08 +0000 2017,"@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day",618,615.0
2,617,115820,True,Tue Oct 31 22:16:32 +0000 2017,Way to drop the ball on customer service @115821 so pissed right now!,615,NaN

In [92]:
import sqlite3
import pandas as pd
import os

DB_PATH = "../data/twcs.db"

# Remove old database if you are re-running this from scratch
if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

conn = sqlite3.connect(DB_PATH)

print("Database created:", DB_PATH)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '../data/twcs.db'

In [ ]:
columns_needed = [
    "tweet_id",
    "author_id",
    "inbound",
    "created_at",
    "in_response_to_tweet_id"
]

first_chunk = True

for chunk in pd.read_csv(
    DATA_PATH,
    usecols=columns_needed,
    chunksize=100_000
):
    
    chunk.to_sql(
        "tweets",
        conn,
        if_exists="replace" if first_chunk else "append",
        index=False
    )
    
    first_chunk = False

print("Finished loading tweet relationships.")

Finished loading tweet relationships.

In [ ]:
conn.execute("""
CREATE INDEX idx_tweet_id
ON tweets(tweet_id)
""")

conn.execute("""
CREATE INDEX idx_parent_id
ON tweets(in_response_to_tweet_id)
""")

conn.execute("""
CREATE INDEX idx_author_id
ON tweets(author_id)
""")

conn.commit()

print("Indexes created.")

Indexes created.

In [ ]:
result = conn.execute(
    "SELECT COUNT(*) FROM tweets"
).fetchone()

print("Tweets stored:", result[0])

Tweets stored: 2811774

In [ ]:
amazon_count = conn.execute("""
SELECT COUNT(*)
FROM tweets
WHERE author_id = 'AmazonHelp'
""").fetchone()[0]

print("AmazonHelp tweets:", amazon_count)

AmazonHelp tweets: 169840

In [ ]:
amazon_ids = pd.read_sql_query("""
    SELECT tweet_id
    FROM tweets
    WHERE author_id = 'AmazonHelp'
""", conn)

print("AmazonHelp tweets:", len(amazon_ids))
print(amazon_ids.head())

AmazonHelp tweets: 169840
   tweet_id
0       269
1       273
2       275
3       324
4       615

In [ ]:
parent_df = pd.read_sql_query("""
    SELECT tweet_id, in_response_to_tweet_id
    FROM tweets
""", conn)

print("Rows loaded:", len(parent_df))

Rows loaded: 2811774

In [ ]:
parent_map = dict(
    zip(
        parent_df["tweet_id"],
        parent_df["in_response_to_tweet_id"]
    )
)

print("Parent relationships:", len(parent_map))

Parent relationships: 2811774

In [ ]:
root_cache = {}

def get_root(tweet_id):

    # Already calculated?
    if tweet_id in root_cache:
        return root_cache[tweet_id]

    current = tweet_id
    path = []
    visited = set()

    while current is not None:

        # If we already know the root
        if current in root_cache:
            root = root_cache[current]
            break

        # Protect against cycles
        if current in visited:
            root = current
            break

        visited.add(current)
        path.append(current)

        parent = parent_map.get(current)

        # No parent → this is the root
        if pd.isna(parent):
            root = current
            break

        current = parent

    # Cache all tweets in this path
    for tweet in path:
        root_cache[tweet] = root

    return root

In [ ]:
print("Root of 615:", get_root(615))
print("Root of 616:", get_root(616))
print("Root of 617:", get_root(617))

Root of 615: 617.0
Root of 616: 617.0
Root of 617: 617.0

In [ ]:
amazon_ids["conversation_id"] = amazon_ids["tweet_id"].apply(get_root)

print(amazon_ids.head())

   tweet_id  conversation_id
0       269            272.0
1       273            272.0
2       275            272.0
3       324            325.0
4       615            617.0

In [ ]:
unique_conversations = amazon_ids["conversation_id"].nunique()

print(
    "Unique conversations involving AmazonHelp:",
    unique_conversations
)

Unique conversations involving AmazonHelp: 82534

In [ ]:
conversation_lengths = (
    amazon_ids
    .groupby("conversation_id")
    .size()
)

In [ ]:
print(conversation_lengths.describe())

count    82534.000000
mean         2.057819
std          2.140102
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max        162.000000
dtype: float64

In [ ]:
length_distribution = (
    conversation_lengths
    .value_counts()
    .sort_index()
)

print(length_distribution.head(15))

1     41575
2     21928
3      9463
4      4393
5      2126
6      1070
7       587
8       374
9       273
10      156
11      127
12       82
13       68
14       45
15       46
Name: count, dtype: int64

In [ ]:
multi_turn = (conversation_lengths >= 2).sum()
total_conversations = len(conversation_lengths)

print("Total conversations:", total_conversations)
print("Conversations with 2+ AmazonHelp replies:", multi_turn)
print(
    "Percentage with 2+ replies:",
    round(100 * multi_turn / total_conversations, 2),
    "%"
)

Total conversations: 82534
Conversations with 2+ AmazonHelp replies: 40959
Percentage with 2+ replies: 49.63 %

In [ ]:
print(
    "Average AmazonHelp replies per conversation:",
    round(conversation_lengths.mean(), 2)
)

print(
    "Median AmazonHelp replies per conversation:",
    conversation_lengths.median()
)

Average AmazonHelp replies per conversation: 2.06
Median AmazonHelp replies per conversation: 1.0

In [ ]:
multi_turn = (conversation_lengths >= 2).sum()
total_conversations = len(conversation_lengths)

print("Total conversations:", total_conversations)
print("Conversations with 2+ AmazonHelp replies:", multi_turn)
print(
    "Percentage with 2+ replies:",
    round(100 * multi_turn / total_conversations, 2),
    "%"
)

Total conversations: 82534
Conversations with 2+ AmazonHelp replies: 40959
Percentage with 2+ replies: 49.63 %

In [ ]:
amazon_conversation_ids = set(
    amazon_ids["conversation_id"].dropna()
)

print(
    "AmazonHelp conversation IDs:",
    len(amazon_conversation_ids)
)

AmazonHelp conversation IDs: 82534

In [ ]:
customer_reply_ids = pd.read_sql_query("""
    SELECT tweet_id, in_response_to_tweet_id
    FROM tweets
    WHERE inbound = 1
      AND in_response_to_tweet_id IS NOT NULL
""", conn)

print("Customer replies:", len(customer_reply_ids))

Customer replies: 750497

In [ ]:
all_tweets = pd.read_sql_query("""
    SELECT tweet_id, in_response_to_tweet_id
    FROM tweets
""", conn)

print("Tweets loaded:", len(all_tweets))

Tweets loaded: 2811774

In [ ]:
all_tweets["conversation_id"] = all_tweets["tweet_id"].apply(get_root)

print("Conversation IDs calculated.")

Conversation IDs calculated.

In [ ]:
amazon_conversations = all_tweets[
    all_tweets["conversation_id"].isin(
        amazon_conversation_ids
    )
]

print(
    "Tweets belonging to AmazonHelp conversations:",
    len(amazon_conversations)
)

Tweets belonging to AmazonHelp conversations: 374042

In [ ]:
total_message_lengths = (
    amazon_conversations
    .groupby("conversation_id")
    .size()
)

print(total_message_lengths.describe())

count    82534.000000
mean         4.531975
std          5.322001
min          2.000000
25%          2.000000
50%          3.000000
75%          5.000000
max        448.000000
dtype: float64

In [ ]:
print("\nConversation length distribution:")

print(
    total_message_lengths
    .value_counts()
    .sort_index()
    .head(20)
)

Conversation length distribution:
2     31290
3     11572
4     14014
5      6060
6      5947
7      3159
8      2797
9      1701
10     1385
11      952
12      713
13      500
14      391
15      285
16      289
17      208
18      180
19      145
20      113
21       96
Name: count, dtype: int64

In [ ]:
longer_conversations = (total_message_lengths >= 4).sum()
total_conversations = len(total_message_lengths)

print("Total AmazonHelp conversations:", total_conversations)
print("Conversations with 4+ messages:", longer_conversations)
print(
    "Percentage with 4+ messages:",
    round(
        100 * longer_conversations / total_conversations,
        2
    ),
    "%"
)

five_plus = (total_message_lengths >= 5).sum()

print("Conversations with 5+ messages:", five_plus)
print(
    "Percentage with 5+ messages:",
    round(
        100 * five_plus / total_conversations,
        2
    ),
    "%"
)

Total AmazonHelp conversations: 82534
Conversations with 4+ messages: 39672
Percentage with 4+ messages: 48.07 %
Conversations with 5+ messages: 25658
Percentage with 5+ messages: 31.09 %

In [ ]:
candidate_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Uber_Support",
    "SpotifyCares"
]

brand_tweets = pd.read_sql_query("""
    SELECT tweet_id, author_id
    FROM tweets
    WHERE author_id IN (?, ?, ?, ?)
""", conn, params=candidate_brands)

print(brand_tweets["author_id"].value_counts())

author_id
AmazonHelp      169840
AppleSupport    106860
Uber_Support     56270
SpotifyCares     43265
Name: count, dtype: int64

In [ ]:
brand_tweets["conversation_id"] = brand_tweets["tweet_id"].apply(
    get_root
)

print(brand_tweets.head())

   tweet_id   author_id  conversation_id
0       269  AmazonHelp            272.0
1       273  AmazonHelp            272.0
2       275  AmazonHelp            272.0
3       324  AmazonHelp            325.0
4       615  AmazonHelp            617.0

In [ ]:

brand_stats = []

for brand in candidate_brands:

    brand_df = brand_tweets[
        brand_tweets["author_id"] == brand
    ]

    lengths = (
        brand_df
        .groupby("conversation_id")
        .size()
    )

    total = len(lengths)

    brand_stats.append({
        "brand": brand,
        "brand_tweets": len(brand_df),
        "conversations": total,
        "avg_brand_replies": round(lengths.mean(), 2),
        "median_brand_replies": lengths.median()
    })

comparison_df = pd.DataFrame(brand_stats)

comparison_df

,brand,brand_tweets,conversations,avg_brand_replies,median_brand_replies
0,AmazonHelp,169840,82534,2.06,1.0
1,AppleSupport,106860,80702,1.32,1.0
2,Uber_Support,56270,41923,1.34,1.0
3,SpotifyCares,43265,28280,1.53,1.0

In [ ]:
amazon_tweet_map = all_tweets[
    all_tweets["conversation_id"].isin(
        amazon_conversation_ids
    )
][["tweet_id", "conversation_id"]].copy()

print("AmazonHelp tweets mapped:", len(amazon_tweet_map))
print("AmazonHelp conversations:", amazon_tweet_map["conversation_id"].nunique())

AmazonHelp tweets mapped: 374042
AmazonHelp conversations: 82534

In [ ]:
tweet_to_conversation = dict(
    zip(
        amazon_tweet_map["tweet_id"],
        amazon_tweet_map["conversation_id"]
    )
)

print("Tweet → conversation mappings:", len(tweet_to_conversation))

Tweet → conversation mappings: 374042

In [ ]:
conversation_columns = [
    "tweet_id",
    "author_id",
    "inbound",
    "created_at",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]

amazon_parts = []

for chunk in pd.read_csv(
    DATA_PATH,
    usecols=conversation_columns,
    chunksize=100_000
):
    
    # Keep only tweets that belong to AmazonHelp conversations
    mask = chunk["tweet_id"].isin(tweet_to_conversation)
    
    if mask.any():
        part = chunk.loc[mask].copy()
        
        part["conversation_id"] = (
            part["tweet_id"].map(tweet_to_conversation)
        )
        
        amazon_parts.append(part)

print("Chunks collected:", len(amazon_parts))

Chunks collected: 29

In [ ]:
amazon_clean = pd.concat(
    amazon_parts,
    ignore_index=True
)

print("Rows:", len(amazon_clean))
print("Conversations:", amazon_clean["conversation_id"].nunique())

Rows: 374042
Conversations: 82534

In [ ]:
amazon_clean["created_at"] = pd.to_datetime(
    amazon_clean["created_at"]
)

amazon_clean = amazon_clean.sort_values(
    ["conversation_id", "created_at"]
).reset_index(drop=True)

C:\Users\rites\AppData\Local\Temp\ipykernel_7816\30350900.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  amazon_clean["created_at"] = pd.to_datetime(

In [ ]:
amazon_clean[
    amazon_clean["conversation_id"] == 617
][
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text"
    ]
]

,tweet_id,author_id,inbound,created_at,text
9,617,115820,True,2017-10-31 22:16:32+00:00,Way to drop the ball on customer service @115821 so pissed right now!
10,615,AmazonHelp,False,2017-10-31 22:29:00+00:00,"@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN"
11,616,115820,True,2017-10-31 23:22:08+00:00,"@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day"
12,618,AmazonHelp,False,2017-10-31 23:28:00+00:00,@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG
13,619,115820,True,2017-10-31 23:32:26+00:00,"@AmazonHelp I frankly don't have the patience for another chat with your ""customer service"" people today."

In [ ]:
OUTPUT_PATH = "../data/amazonhelp_conversations.csv"

amazon_clean.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Saved:", OUTPUT_PATH)

Saved: ../data/amazonhelp_conversations.csv

In [ ]:
import random

conversation_ids = amazon_clean["conversation_id"].unique()

sample_conversations = random.sample(
    list(conversation_ids),
    20
)

for conv_id in sample_conversations:

    conversation = amazon_clean[
        amazon_clean["conversation_id"] == conv_id
    ]

    print("\n" + "=" * 80)
    print("CONVERSATION:", conv_id)
    print("=" * 80)

    for _, row in conversation.iterrows():

        speaker = (
            "CUSTOMER"
            if row["inbound"]
            else "AMAZONHELP"
        )

        print(f"\n[{speaker}]")
        print(row["text"])

================================================================================
CONVERSATION: 872216.0
================================================================================

[CUSTOMER]
@115821 pls stop sending packages by @115817. Consistently late, poor customer service response. Use @132668 or @916 instead

[AMAZONHELP]
@323751 I'm sorry to hear about the trouble, Amir! Have you had the chance to report these incidents with us? ^HC

================================================================================
CONVERSATION: 2961753.0
================================================================================

[CUSTOMER]
Y otro día más q @116928 m toma el pelo y no me entrega un paquete prioritario. Xo eh q me aseguran q mañana si. Menuda burla de servicio

[AMAZONHELP]
@221293 Hola Mario, lamento el atraso. ¿Has podido hablar con la empresa encargada de la entrega para más detalles? ^LG

[CUSTOMER]
@AmazonHelp Problema logístico. Si no fuera porque me pedisteis el primer paquete y este llega ya tarde...

[AMAZONHELP]
@221293 Mario, ¿podrías informarnos si el pedido fue enviado por Amazon o por un vendedor externo? ^NB

[CUSTOMER]
@AmazonHelp Ahí tienes el número de pedido 407-8517352-5133922 , al que van asociadas ya tres quejas que aunque no sirven para nada me gusta ponerla

[AMAZONHELP]
@221293 Por motivos de seguridad por favor no compartas informaciones sensibles a tu cuenta Mario. Por este medio no tenemos acceso a tu cuenta. Nos podrías confirmar, ¿Tu pedido fue vendido por Amazon o por un vendedor externo? ^JJ

[CUSTOMER]
@AmazonHelp Dos de tres son por vendedor externo y el tercero por Amazon

[AMAZONHELP]
@221293 Mario, gracias por el dato, ¿ya has contactado a los vendedores y a Servicio al Cliente en el caso del pedido gestionado por Amazon? De ser así, ¿qué respuesta te brindaron? ^CB

[CUSTOMER]
@AmazonHelp Todo venía junto en el mismo paquete así que asumo que lo gestiona Amazon. En el primero, el cual se perdió, primero me dijeron que llegaría 3 días después y cuando no llegó y pregunte me dijeron que se había extraviado

[CUSTOMER]
@AmazonHelp En este segundo pues la"entrega garantizada" era hoy pero nada aquí estamos de nuevo sin el paquete. He puesto tres quejas por si sirve de algo

[AMAZONHELP]
@221293 Mario, ¿qué respuesta te brindaron nuestros compañeros de Servicio al Cliente? ^ES

[CUSTOMER]
@AmazonHelp Que lo sentían mucho. Metieron las quejas y en la segunda queja un descuento de 7 euros y jurarme y perjurarme que este nuevo pedido vendría ipsofacto

[AMAZONHELP]
@221293 Comprendo Mario y gracias por el dato, en este caso, si no lo recibes hoy, lo mejor sería consultar nuevamente con Servicio al Cliente ya que nosotros no tenemos acceso a tu cuenta. Si gustas, puedes usar este enlace: https://t.co/OjvUxwnzPe
^CB

================================================================================
CONVERSATION: 874499.0
================================================================================

[CUSTOMER]
@115830 @AmazonHelp you delivered a prime delivery 3 days late, left it in the rain. This is the result. Can I have new books plus refund https://t.co/UnHqQry5eX

[AMAZONHELP]
@327620 Oh no! I'm sorry your order arrived like this! You can view refund/replacement options with us here: https://t.co/7hZIKT4cHB ^KP

================================================================================
CONVERSATION: 2845510.0
================================================================================

[CUSTOMER]
Descuentos en PS4 y PS4 Pro 🎮 ¡Aprovecha! https://t.co/eM0QtzyD8F

[CUSTOMER]
@116875 Precio?

[AMAZONHELP]
@791486 ¡Hola Oscar! Te comento que puedes encontrar todas nuestras ofertas en nuestro sitio web en la sección de Cyber Monday. Acá te dejo un enlace que te lleva directamente a la categoría de Videojuegos en la sección de Cyber Monday: https://t.co/WnLG6YugTF. ^MZ

[CUSTOMER]
@116875 Hola buen día, disculpen compré una Playstation4Pro y no añadí mi juego gratuito por despistado, se puede hacer algo al respecto o ya me fregué???

[AMAZONHELP]
@791887 Hola buen día Luis, ¿podrías confirmarnos si te refieres a alguna promoción específica? En caso de que si, ¿podrías facilitarnos el enlace de la oferta? ^DA

[CUSTOMER]
@AmazonHelp Hola buen día, la promoción es "En la compra de una consola PlayStation PRO 1TB llévate un juego “favorito” para PS4 sin costo", pero por despistado no agregué mi juego gratuito, la consola la adquirí hoy en la mañana, link de la promoción:
https://t.co/l9E6s4o4vV

[AMAZONHELP]
@791887 Gracias por la información Luis, la promoción indica que para recibir el juego, es necesario agregar la consola y el videojuego al carrito de compras y proceder al pago, en donde se verá reflejado el descuento sobre el videojuego seleccionado. ^MZ

[CUSTOMER]
@116875 $$

[CUSTOMER]
@AmazonHelp Si, la regué muy feo, pero gracias por atenderme. 😞

[AMAZONHELP]
@791887 Con gusto Luis. Estamos para ayudarte.
Un saludo,
^DB

[AMAZONHELP]
@792974 ¡Hola Manuel! En este enlace puedes ingresar directamente a la sección de consolas PlayStation 4 de Cyber Monday: https://t.co/56jpvnWFXz. Además puedes ingresar a la sección general de Cyber Monday para ver todas nuestras ofertas. ^MZ

================================================================================
CONVERSATION: 477696.0
================================================================================

[CUSTOMER]
Participate in the Fitbit quiz on the Amazon app today and two lucky winners win a Fitbit Charge 2 and a Fitbit Flex 2! #AppFitnessFest https://t.co/4SLDRsbetb

[CUSTOMER]
@115850 Hello sir how i can see any winners in amazon app

[AMAZONHELP]
@228482 You can find all the contest results here: https://t.co/ICRkX2fNTQ ^SG

================================================================================
CONVERSATION: 2299103.0
================================================================================

[CUSTOMER]
@AmazonHelp my wish lists seem to have vanished🤔 can access them via links i shared with fam but its not on my account and i cant add to it

[AMAZONHELP]
@146547 I apologize for the inconvenience, Melissa! Are you trying to access the list on a mobile device or computer? If computer, please try clearing cache and cookies from the browser and switching browsers. Let us know if that helps! ^CS

[CUSTOMER]
@AmazonHelp none of the above are working😣 it doesnt show up no matter the browser or device, i can only see it via the link. but i want to add more

[AMAZONHELP]
@146547 Please reach out to our wishlist and registries department here: https://t.co/JzP7hlA23B so we can look into this with you. We want to help! ^ZW

================================================================================
CONVERSATION: 2671352.0
================================================================================

[CUSTOMER]
Look what you make me do @115850 #todayithunk #idiomsIRL #comic #watercolour https://t.co/i13y6iAG96

[AMAZONHELP]
@752232 #todayithunk would be a normal day. But then came this!! We are never ever getting over it. 💙 ^AB

[CUSTOMER]
@AmazonHelp :D 💞

================================================================================
CONVERSATION: 2450123.0
================================================================================

[CUSTOMER]
@amazonhelp why can’t I set my location to Sweden for weather? Was excited about #alexa on my new @118117 one but this is annoying https://t.co/pUX1GjKfrN

[AMAZONHELP]
@702210 That is odd, Jonathan! I'd like to have someone troubleshoot this with you. Please contact us: here https://t.co/hApLpMlfHN ^AD

================================================================================
CONVERSATION: 2924610.0
================================================================================

[CUSTOMER]
I want you aware that I am seeking my issue to be rectified in 2 business days @115821 @AmazonHelp wasting #cybermonday with #Amazon? Don’t let me down. Excited to see where my items are in this world. https://t.co/yUlvv4ZPCu

[AMAZONHELP]
@188153 Thanks for contacting us over Twitter. Without posting any personal or account information, can you tell us a bit more about the issue? ^GG

[CUSTOMER]
@AmazonHelp Made a purchase at the same time for 2 items Mon. Notified 1 was shipped, went to track the other and it said “this was cancelled”. However, i didn’t cancel it. I received a confirmation that it went through and it gave me est arrival dates. My card was charged for both items.

[CUSTOMER]
@AmazonHelp Now I have to wait 2 days for the 3rd party seller to ‘figure it out’ ? I need the item and if this 2 days inhibits my holiday plans I would like to search else where for my missing item. Settlement code 02796R - would rather get a refund to find my gift elsewhere.

[AMAZONHELP]
@188153 I'm sorry for the difficulties you've had with your orders. Since we're not able to view account details via Twitter, please contact us via phone or chat so we may look further into this with you by using this link: https://t.co/hApLpMlfHN ^KL

[CUSTOMER]
@AmazonHelp I did in chat. I have to wait 2 days to hear from the seller. I need my item expedited at this point.  Order ID 113-4937950-3648256 - follow the journey.

================================================================================
CONVERSATION: 2568098.0
================================================================================

[CUSTOMER]
Love when @115830 prime one day delivery takes 3 days and still hasn't arrived.

[AMAZONHELP]
@728445 I'm sorry for the disappointment, Daniel. Have we missed the estimated delivery date shown here: https://t.co/aaDyEz1VgE ? ^FD

[CUSTOMER]
@AmazonHelp Yeah the original estimate was the 28th and everyday after it said that it would arrive and it never did.

[AMAZONHELP]
@728445 When you have a moment, please phone us here: https://t.co/JzP7hlA23B to report this and discuss available options. ^LB

================================================================================
CONVERSATION: 2612323.0
================================================================================

[CUSTOMER]
@115821 when you pre order a game off amazon should it come on the day if release? Surely that’s the whole point of a pre order? Well yeah mine comes a day after release, please explain.. oh and a mate has already had his and he lives in the same village....

[AMAZONHELP]
@738621 I'm sorry for the trouble, Stefan! Could you confirm if your order was eligible for Release Day Delivery: https://t.co/WBcwIjOKt4 ? This delivery option is only available for items displaying the Release Day Delivery offer message on their product description pages. ^SD

================================================================================
CONVERSATION: 2897660.0
================================================================================

[CUSTOMER]
@AmazonHelp can I have an email to contact you please. helpline not listening to anything I'm saying

[AMAZONHELP]
@147110 I'm sorry for the troubles! What information or options were we able to provide? ^TK

[CUSTOMER]
@AmazonHelp My prime membership has been refunded for Nov and I have cancelled prime.  Still annoyed by your deceptive advertising

================================================================================
CONVERSATION: 2967778.0
================================================================================

[CUSTOMER]
@115821 here’s an idea... how ‘bout NOT having the product name on the outside of the delivered box... some of us like to keep our gifts secret from other members of our family.  Thanks

[AMAZONHELP]
@805475 I'm sorry for the poor experience, Tammy! To cut down on packaging, we've started shipping certain items in manufacturer packaging. When checking out, there should be an option to ship the order in an Amazon box! More info here: https://t.co/oF0wfkwkrc ^WT

[CUSTOMER]
@AmazonHelp Good to know!  I used to only use the gift option if it was shipping to another person directly.  Maybe the change could be made more obvious on the checkout page.  Thanks for the quick reply!

[AMAZONHELP]
@805475 You're very welcome. We greatly appreciate the feedback, and your patience! ^JR

================================================================================
CONVERSATION: 971299.0
================================================================================

[CUSTOMER]
@115850 Your service has deteriorated. I got sms &amp; account update as product delivered,but it hasn't been delivered in fact.Fraudulence..

[CUSTOMER]
@115850 Even you need to improve your courier service &amp; that of your associated partners including Amazon Transport Services

[AMAZONHELP]
@350450 incorrect tracking scan update. Kindly contact us here: https://t.co/yMYPfB1xLa and we'll sort this out. 2/2 ^SH

[AMAZONHELP]
@350450 I'm sorry you haven't received the order even though the tracking is updated as delivered. This could be due to 1/2 ^SH

[CUSTOMER]
@AmazonHelp Please note that you need to fix your ATS, as me and my known person, in both of our cases, the courier is Amazon Transport Services (ATS)

[AMAZONHELP]
@350450 Sorry for the delivery issue, Pankaj. Please connect with us using the link provided earlier, and we'll check this. ^KA

================================================================================
CONVERSATION: 2631454.0
================================================================================

[CUSTOMER]
Way to go @AmazonHelp. Thanks for delaying Ultra Sun/Moon until Wednesday. And I really appreciate you letting me know only today. Not earlier this week when you knew you weren’t gonna be able to fulfill my order. A+ job.

[AMAZONHELP]
@743052 I'm sorry to hear about the delay!  Try reaching out to us here:
 https://t.co/hApLpMlfHN so we can look at what options there might be to assist. ^WB

================================================================================
CONVERSATION: 352905.0
================================================================================

[CUSTOMER]
@AmazonHelp Sir, how you can send me subscription item on one time purchase rate, after numerous reminders in these 2 days your side response is pathetic. After subscribing, rarely i see the amount of subscribed product you send.

[AMAZONHELP]
@199910 I understand your concern. Could you confirm sharing your details on the link provided earlier? ^JS

[CUSTOMER]
@AmazonHelp which link? please share link!

[AMAZONHELP]
@199910 Please share your details here: https://t.co/beaaDm0muc and we'll contact you soon.​ ^JS

[CUSTOMER]
@AmazonHelp contact number 9752092631

[AMAZONHELP]
@199910 We do not have access to your details over social platform. Please use the link given earlier and fill the form. We will check and connect with you accordingly. ^RW

[AMAZONHELP]
@199910 Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ ^RW

[CUSTOMER]
@AmazonHelp Sir, I had filled the details in your respective link. Please do the needful.

[AMAZONHELP]
@199910 Thank you for sharing your details, we'll get back to you soon. ^SU

[CUSTOMER]
@AmazonHelp Invoice https://t.co/VIjKF6LK2E

[CUSTOMER]
@AmazonHelp Subscription amount https://t.co/XwUdiUKuQb

[AMAZONHELP]
@199910 We have replied to your DM. Please check. ^MJ

[CUSTOMER]
@AmazonHelp I hope you are referring this DM, but it is not all fruitful for me and in mail also nothing had came. https://t.co/5SdXdh2hjo

[CUSTOMER]
@AmazonHelp Now simply answer my question why 1 tym amount u ppl chargd, when u send me monthly subscription item. Plz be specific.

[AMAZONHELP]
@199910 That's quite a remark, Venkat. Apologies. Please reply to the email we've sent to your registered email. We'll check your concern and help you further. ^SV

================================================================================
CONVERSATION: 286351.0
================================================================================

[CUSTOMER]
Why can't I watch last 6 episodes of Suits Season 6 now ? It was available until today morning. @119625

[AMAZONHELP]
@184219 library. We will let you know when these episodes are back. We’re really sorry for the inconvenience caused. [2/2] ^HA

[AMAZONHELP]
@184219 Unfortunately these episodes/ this episode is no longer available. We’re constantly adding new content to our [1/2] ^HA

================================================================================
CONVERSATION: 1442962.0
================================================================================

[CUSTOMER]
@115830 One of my packages was returned and I was promised a refund for it. The package was returned on November 12th but I am yet to receive my refund.

Order # 202-5689764-4845964

[AMAZONHELP]
@454811 I'm so sorry for the delay of your refund! We'd like to help, please reach us by phone or chat here: https://t.co/JzP7hlA23B ^AG

================================================================================
CONVERSATION: 2715207.0
================================================================================

[CUSTOMER]
@115850 ....can I have the status of refund for 403-2164374-0227518 please?

[AMAZONHELP]
@762204 Please don't provide your order details, as we consider it to be personal information. Our Twitter page is visible to the public. (2/2) ^VM

[AMAZONHELP]
@762204 We'd love to help and check out the status of your refund. However, this being a public platform we would be unable to access your account/order info here. Kindly reach us via https://t.co/CNHA4voaWH and we'll reach out to you soon.(1/2) ^VM

================================================================================
CONVERSATION: 446783.0
================================================================================

[CUSTOMER]
Se "de graça, até injeção na testa", nada como um bolinho de aniversário da @117086 só porque tava com Bernadette. https://t.co/SLa0x3Ov12

[AMAZONHELP]
@220843 Olá Tuca, e o que achou do bolo? 😍 ^DA

[CUSTOMER]
@AmazonHelp tava uma delicinha. no trabalho, todo mundo perto de mim provou um pedacinho e adorou

[AMAZONHELP]
@220843 Que deliciaaaaa Tuca! Manda um pedaço pra gente! Eu amo o chocolate! Rs rs rs 😍🎂 ^JJ

[CUSTOMER]
@AmazonHelp já foi tudo :(

[AMAZONHELP]
@220843 Nós aqui estamos só com comida saudável!😕🍏😁 Aquí está faltando o chocolate!😅 ^HC https://t.co/NGwQrMyPHU

[CUSTOMER]
@AmazonHelp que terrível? como um dino dessa tamanho consegue se sustentar só com essas frutinhas?

[AMAZONHELP]
@220843 🙈Ele não só come frutinhas,não.🙊 Acabamos de descobrir que o Ruperto quebrou o seu regime!😱😋 ^HC https://t.co/6iAJFF5xSB

[CUSTOMER]
@AmazonHelp aew!

[AMAZONHELP]
@220843 Esse era o café da tarde Tuca! Ruperto come muito! Rs rs rs. Quais são os seus escritores favoritos Tuca? Escreve para a gente no seguinte link: https://t.co/kUkXHFkYWd    ^JJ

[CUSTOMER]
@AmazonHelp simbora

[CUSTOMER]
@AmazonHelp bah, não to lembrando da minha senha agora. outra hora então.

[AMAZONHELP]
@220843 Tuca, assim que você lembrar da senha, pode responder o link fornecido. 😉✨ ^NB

[CUSTOMER]
@AmazonHelp prontinho ;)

[AMAZONHELP]
@220843 🤗 Vamos ler sua resposta em breve, Tuca! ^LG

[AMAZONHELP]
@220843 Oi Tuca! Você pode falar pra gente qual é seu endereço no seguinte link: https://t.co/kUkXHFCzNL  ? ^JJ

[CUSTOMER]
@AmazonHelp OXE, mandei foi agora. que cês tão aprontando?

In [ ]:
import numpy as np

np.random.seed(42)

all_amazon_conversations = amazon_clean[
    "conversation_id"
].unique()

sampled_conversations = np.random.choice(
    all_amazon_conversations,
    size=1000,
    replace=False
)

intent_sample = amazon_clean[
    amazon_clean["conversation_id"].isin(
        sampled_conversations
    )
].copy()

print(
    "Sampled conversations:",
    intent_sample["conversation_id"].nunique()
)

print(
    "Sampled messages:",
    len(intent_sample)
)

Sampled conversations: 1000
Sampled messages: 4874

In [ ]:
customer_messages = intent_sample[
    intent_sample["inbound"] == True
].copy()

print("Customer messages:", len(customer_messages))

Customer messages: 2685

In [ ]:
for i, (_, row) in enumerate(
    customer_messages[
        ["conversation_id", "text"]
    ].sample(50, random_state=42).iterrows()
):

    print("\n" + "=" * 80)
    print(f"Example {i + 1}")
    print("Conversation:", row["conversation_id"])
    print("=" * 80)
    print(row["text"])

================================================================================
Example 1
Conversation: 397889.0
================================================================================
@Tesco That's alright, I can't complain about a promotion ending, I should have been quicker!

================================================================================
Example 2
Conversation: 590810.0
================================================================================
@120533 super votre service client..et votre service de livraison..je devais être livrée le 1er décembre bien évidemment je n'ai rien eu et votre service client qd il répond..ne sait pas où est le colis et ne sait pas qd il sera livré👏👏👏👏👏 AUCUNE AIDE POURRI

================================================================================
Example 3
Conversation: 385059.0
================================================================================
@AmazonHelp Its quite urgent...There is a marriage in my family nd i m supposed to wear it...i hope u wil understand

================================================================================
Example 4
Conversation: 2710877.0
================================================================================
@AmazonHelp Thanks!!!
But till now my complete experience with you guys was very bad.
I think your customer care team and customer escalation team are working for himself , not for a customer. https://t.co/0b3lI59lba

================================================================================
Example 5
Conversation: 1274819.0
================================================================================
@115850 @115850  you never sent me the email.

================================================================================
Example 6
Conversation: 230066.0
================================================================================
@115850 Called the Amazon delivery agent, he told me it was cancelled and in my order detail. Why does it says I cancelled it ?M I goin 2 get d phn?

================================================================================
Example 7
Conversation: 397889.0
================================================================================
@Tesco When can I collect my free copy ? 😚 #Asdasucks

================================================================================
Example 8
Conversation: 1203382.0
================================================================================
@115821 @AmazonHelp thanks to ur driver 2day my bf n I lost out on our #snes bc they didn't use the locker but "delivered" them somewhere

================================================================================
Example 9
Conversation: 1203382.0
================================================================================
@AmazonHelp It was your delivery person. AMZL US

================================================================================
Example 10
Conversation: 1699747.0
================================================================================
@AmazonHelp Sure. Just did.

================================================================================
Example 11
Conversation: 1557995.0
================================================================================
@AmazonHelp Es trifft einfach keine Antwortmöglichkeit darauf zu https://t.co/NRDVHohFwz

================================================================================
Example 12
Conversation: 229787.0
================================================================================
@115850 @115821 Sir its 10-13 oct but I booked the SD memory card yesterday can u pls pls arrange asap delivery of my order.

================================================================================
Example 13
Conversation: 297372.0
================================================================================
@AmazonHelp Thankyou, I have sent an email

================================================================================
Example 14
Conversation: 2393509.0
================================================================================
worst service @115850  cash load service is worst
not received my cash in amazon pay balance

================================================================================
Example 15
Conversation: 1264612.0
================================================================================
amazonもう許さねえからな～？

================================================================================
Example 16
Conversation: 1718733.0
================================================================================
@AmazonHelp 408-7381410-8288305 refund not yet given amazon must pay panality as 5 days passed for amount ₹699

================================================================================
Example 17
Conversation: 250048.0
================================================================================
@AmazonHelp Is the Echo Dot being released in India the second gen edition?

================================================================================
Example 18
Conversation: 704351.0
================================================================================
@116316  Hallo, wieso steht beim Prime Versand bei euch ein Liefertermin am Dienstag 28.11.17 wenn man jetzt bestellt. Ich bin Prime Kunde. Danke und Gruß

================================================================================
Example 19
Conversation: 1274819.0
================================================================================
@115850 Kudos to you! Cancelled my order twice. After waiting for 14+ days I am left with exactly Nothing 🙏 #HopelessAmazon

================================================================================
Example 20
Conversation: 753529.0
================================================================================
@AmazonHelp @115850 have given all my details and comments.. even spoken to a customer representative.. what more do I need to do????

================================================================================
Example 21
Conversation: 1582547.0
================================================================================
@115850 mobile recharge isn't working on your app, what happened??

================================================================================
Example 22
Conversation: 2318999.0
================================================================================
@AmazonHelp Have created replacement but I needed little urgent can you help on this

================================================================================
Example 23
Conversation: 397889.0
================================================================================
@Tesco Be nice if my local store had any, as it's a good price, plenty of season passes in stock, judging from the amount of dummy season pass boxes that ol are on the shelves. But no actual full game. 😂😂😂 Lucky it just over the road from work.

================================================================================
Example 24
Conversation: 182627.0
================================================================================
@AmazonHelp Okay, it has been three business days, but you've already processed the refund, so thanks.

================================================================================
Example 25
Conversation: 397889.0
================================================================================
@Tesco @484294 Shoutout to Gregs gran

================================================================================
Example 26
Conversation: 777156.0
================================================================================
今来たんだけど何これ
Amazon使ったことないんだけど https://t.co/xaxy4o1kcx

================================================================================
Example 27
Conversation: 334500.0
================================================================================
@AmazonHelp Is that who sold it?

================================================================================
Example 28
Conversation: 1504117.0
================================================================================
Amazonで買ったズボンのここが凄い https://t.co/OmQZ5BzLeT

================================================================================
Example 29
Conversation: 1133968.0
================================================================================
@117804 Como eu sei se meu pedido foi aprovado ou não?

================================================================================
Example 30
Conversation: 1254206.0
================================================================================
@AmazonHelp can y’all just delete the account or ??

================================================================================
Example 31
Conversation: 644861.0
================================================================================
Way to go @115821! You keep making promises you can’t keep.
You promise two day shipping: Doesn’t Show. (you lost it)
You promise you’ll cover the cost of one day shipping: Not Available.
Last promise is to refund my money: TBD

================================================================================
Example 32
Conversation: 396929.0
================================================================================
@AmazonHelp Yes, I did.

================================================================================
Example 33
Conversation: 2302205.0
================================================================================
@AmazonHelp First delivery which was placed in AUGUST, still says dispatched. And second order says out for delivery has been like this for 3 days and I paid £5.99 for next day?

================================================================================
Example 34
Conversation: 1753337.0
================================================================================
@AmazonHelp Para qué preguntan ? Siguen en la misma línea . INCREIBLE

================================================================================
Example 35
Conversation: 1086789.0
================================================================================
amazon showing order status delievered from past 3 days but still waiting to get my order amazon sucks @AmazonHelp

================================================================================
Example 36
Conversation: 397889.0
================================================================================
@Tesco Think you should put up job vacancies ... From https://t.co/96HJ7tp64k

================================================================================
Example 37
Conversation: 453185.0
================================================================================
@AmazonHelp Why did it take them almost 3 days to prepare the shipment.

================================================================================
Example 38
Conversation: 814234.0
================================================================================
@AmazonHelp Delivery wise, what's the difference between getting something delivered home and getting something delivered to work?

================================================================================
Example 39
Conversation: 2599086.0
================================================================================
@AmazonHelp Besides, I no longer want an account with Amazon. Keep it frozen for all I care, or destroy it. All I'm asking is that you not charge me for prime on an account which you have frozen.

================================================================================
Example 40
Conversation: 2317958.0
================================================================================
Ich kann bald wieder backen! 😍

================================================================================
Example 41
Conversation: 838313.0
================================================================================
@AmazonHelp Acabo de recibir respuesta de att cliente de amazon. Si no lo recibo hoy, os detallare el caso por su enlace. Muchas gracias, muy amables.

================================================================================
Example 42
Conversation: 234514.0
================================================================================
@AmazonHelp I have half marathon coming soon..need to prepare beforehand..anyways thanks for looking and supporting for my run!

================================================================================
Example 43
Conversation: 1258534.0
================================================================================
@AmazonHelp Also kann ich irgendwann wieder mit Bankeinzug zahlen oder muss ich mir jetzt extra eine Kreditkarte anlegen um nicht mehr prepaid zuzahlen?

================================================================================
Example 44
Conversation: 2671370.0
================================================================================
@115850 @AmazonHelp Issues in delivery for past 4 packages, same repeats for reverse pickup.

================================================================================
Example 45
Conversation: 1360037.0
================================================================================
@AmazonHelp Another prime fail!
I really don’t know what I pay for your absolute dire service! I wouldn’t recommend anyone to prime!
#fail https://t.co/e5x4LgAXr4

================================================================================
Example 46
Conversation: 315761.0
================================================================================
@AmazonHelp No, phoned you 5 times over  last 2 weeks(diff orders-same issue) yesterday a supervisor promised redelivery today. Just NOW got delay msg!

================================================================================
Example 47
Conversation: 807300.0
================================================================================
Amazon say they are contacting the carrier to make sure it WWE 2K18 Deluxe Edition gets to me tomorrow morning

================================================================================
Example 48
Conversation: 397889.0
================================================================================
@Tesco Be a lad and follow me would you?

================================================================================
Example 49
Conversation: 1649115.0
================================================================================
@AmazonHelp so it’s “delivered” - I call Immediately to say it hasn’t been delivered &amp; CSR says to “wait a day”! 👌🏻🙄 #PrimeMemberForWhat https://t.co/GipMNRIWMw

================================================================================
Example 50
Conversation: 1133968.0
================================================================================
@117804 compreeeei &lt;3

In [ ]:
intent_sample.to_csv(
    "../data/amazonhelp_intent_sample.csv",
    index=False
)

print("Intent sample saved.")

Intent sample saved.

In [ ]:
# Sample 200 customer messages for intent discovery

intent_examples = customer_messages[
    ["conversation_id", "text"]
].sample(
    200,
    random_state=42
).reset_index(drop=True)

print("Examples:", len(intent_examples))

Examples: 200

In [ ]:
for i, row in intent_examples.iloc[:50].iterrows():

    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 1}")
    print("=" * 80)
    print(row["text"])

================================================================================
EXAMPLE 1
================================================================================
@Tesco That's alright, I can't complain about a promotion ending, I should have been quicker!

================================================================================
EXAMPLE 2
================================================================================
@120533 super votre service client..et votre service de livraison..je devais être livrée le 1er décembre bien évidemment je n'ai rien eu et votre service client qd il répond..ne sait pas où est le colis et ne sait pas qd il sera livré👏👏👏👏👏 AUCUNE AIDE POURRI

================================================================================
EXAMPLE 3
================================================================================
@AmazonHelp Its quite urgent...There is a marriage in my family nd i m supposed to wear it...i hope u wil understand

================================================================================
EXAMPLE 4
================================================================================
@AmazonHelp Thanks!!!
But till now my complete experience with you guys was very bad.
I think your customer care team and customer escalation team are working for himself , not for a customer. https://t.co/0b3lI59lba

================================================================================
EXAMPLE 5
================================================================================
@115850 @115850  you never sent me the email.

================================================================================
EXAMPLE 6
================================================================================
@115850 Called the Amazon delivery agent, he told me it was cancelled and in my order detail. Why does it says I cancelled it ?M I goin 2 get d phn?

================================================================================
EXAMPLE 7
================================================================================
@Tesco When can I collect my free copy ? 😚 #Asdasucks

================================================================================
EXAMPLE 8
================================================================================
@115821 @AmazonHelp thanks to ur driver 2day my bf n I lost out on our #snes bc they didn't use the locker but "delivered" them somewhere

================================================================================
EXAMPLE 9
================================================================================
@AmazonHelp It was your delivery person. AMZL US

================================================================================
EXAMPLE 10
================================================================================
@AmazonHelp Sure. Just did.

================================================================================
EXAMPLE 11
================================================================================
@AmazonHelp Es trifft einfach keine Antwortmöglichkeit darauf zu https://t.co/NRDVHohFwz

================================================================================
EXAMPLE 12
================================================================================
@115850 @115821 Sir its 10-13 oct but I booked the SD memory card yesterday can u pls pls arrange asap delivery of my order.

================================================================================
EXAMPLE 13
================================================================================
@AmazonHelp Thankyou, I have sent an email

================================================================================
EXAMPLE 14
================================================================================
worst service @115850  cash load service is worst
not received my cash in amazon pay balance

================================================================================
EXAMPLE 15
================================================================================
amazonもう許さねえからな～？

================================================================================
EXAMPLE 16
================================================================================
@AmazonHelp 408-7381410-8288305 refund not yet given amazon must pay panality as 5 days passed for amount ₹699

================================================================================
EXAMPLE 17
================================================================================
@AmazonHelp Is the Echo Dot being released in India the second gen edition?

================================================================================
EXAMPLE 18
================================================================================
@116316  Hallo, wieso steht beim Prime Versand bei euch ein Liefertermin am Dienstag 28.11.17 wenn man jetzt bestellt. Ich bin Prime Kunde. Danke und Gruß

================================================================================
EXAMPLE 19
================================================================================
@115850 Kudos to you! Cancelled my order twice. After waiting for 14+ days I am left with exactly Nothing 🙏 #HopelessAmazon

================================================================================
EXAMPLE 20
================================================================================
@AmazonHelp @115850 have given all my details and comments.. even spoken to a customer representative.. what more do I need to do????

================================================================================
EXAMPLE 21
================================================================================
@115850 mobile recharge isn't working on your app, what happened??

================================================================================
EXAMPLE 22
================================================================================
@AmazonHelp Have created replacement but I needed little urgent can you help on this

================================================================================
EXAMPLE 23
================================================================================
@Tesco Be nice if my local store had any, as it's a good price, plenty of season passes in stock, judging from the amount of dummy season pass boxes that ol are on the shelves. But no actual full game. 😂😂😂 Lucky it just over the road from work.

================================================================================
EXAMPLE 24
================================================================================
@AmazonHelp Okay, it has been three business days, but you've already processed the refund, so thanks.

================================================================================
EXAMPLE 25
================================================================================
@Tesco @484294 Shoutout to Gregs gran

================================================================================
EXAMPLE 26
================================================================================
今来たんだけど何これ
Amazon使ったことないんだけど https://t.co/xaxy4o1kcx

================================================================================
EXAMPLE 27
================================================================================
@AmazonHelp Is that who sold it?

================================================================================
EXAMPLE 28
================================================================================
Amazonで買ったズボンのここが凄い https://t.co/OmQZ5BzLeT

================================================================================
EXAMPLE 29
================================================================================
@117804 Como eu sei se meu pedido foi aprovado ou não?

================================================================================
EXAMPLE 30
================================================================================
@AmazonHelp can y’all just delete the account or ??

================================================================================
EXAMPLE 31
================================================================================
Way to go @115821! You keep making promises you can’t keep.
You promise two day shipping: Doesn’t Show. (you lost it)
You promise you’ll cover the cost of one day shipping: Not Available.
Last promise is to refund my money: TBD

================================================================================
EXAMPLE 32
================================================================================
@AmazonHelp Yes, I did.

================================================================================
EXAMPLE 33
================================================================================
@AmazonHelp First delivery which was placed in AUGUST, still says dispatched. And second order says out for delivery has been like this for 3 days and I paid £5.99 for next day?

================================================================================
EXAMPLE 34
================================================================================
@AmazonHelp Para qué preguntan ? Siguen en la misma línea . INCREIBLE

================================================================================
EXAMPLE 35
================================================================================
amazon showing order status delievered from past 3 days but still waiting to get my order amazon sucks @AmazonHelp

================================================================================
EXAMPLE 36
================================================================================
@Tesco Think you should put up job vacancies ... From https://t.co/96HJ7tp64k

================================================================================
EXAMPLE 37
================================================================================
@AmazonHelp Why did it take them almost 3 days to prepare the shipment.

================================================================================
EXAMPLE 38
================================================================================
@AmazonHelp Delivery wise, what's the difference between getting something delivered home and getting something delivered to work?

================================================================================
EXAMPLE 39
================================================================================
@AmazonHelp Besides, I no longer want an account with Amazon. Keep it frozen for all I care, or destroy it. All I'm asking is that you not charge me for prime on an account which you have frozen.

================================================================================
EXAMPLE 40
================================================================================
Ich kann bald wieder backen! 😍

================================================================================
EXAMPLE 41
================================================================================
@AmazonHelp Acabo de recibir respuesta de att cliente de amazon. Si no lo recibo hoy, os detallare el caso por su enlace. Muchas gracias, muy amables.

================================================================================
EXAMPLE 42
================================================================================
@AmazonHelp I have half marathon coming soon..need to prepare beforehand..anyways thanks for looking and supporting for my run!

================================================================================
EXAMPLE 43
================================================================================
@AmazonHelp Also kann ich irgendwann wieder mit Bankeinzug zahlen oder muss ich mir jetzt extra eine Kreditkarte anlegen um nicht mehr prepaid zuzahlen?

================================================================================
EXAMPLE 44
================================================================================
@115850 @AmazonHelp Issues in delivery for past 4 packages, same repeats for reverse pickup.

================================================================================
EXAMPLE 45
================================================================================
@AmazonHelp Another prime fail!
I really don’t know what I pay for your absolute dire service! I wouldn’t recommend anyone to prime!
#fail https://t.co/e5x4LgAXr4

================================================================================
EXAMPLE 46
================================================================================
@AmazonHelp No, phoned you 5 times over  last 2 weeks(diff orders-same issue) yesterday a supervisor promised redelivery today. Just NOW got delay msg!

================================================================================
EXAMPLE 47
================================================================================
Amazon say they are contacting the carrier to make sure it WWE 2K18 Deluxe Edition gets to me tomorrow morning

================================================================================
EXAMPLE 48
================================================================================
@Tesco Be a lad and follow me would you?

================================================================================
EXAMPLE 49
================================================================================
@AmazonHelp so it’s “delivered” - I call Immediately to say it hasn’t been delivered &amp; CSR says to “wait a day”! 👌🏻🙄 #PrimeMemberForWhat https://t.co/GipMNRIWMw

================================================================================
EXAMPLE 50
================================================================================
@117804 compreeeei &lt;3

In [ ]:
for i, row in intent_examples.iloc[50:100].iterrows():

    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 1}")
    print("=" * 80)
    print(row["text"])

================================================================================
EXAMPLE 51
================================================================================
@AmazonHelp Have already reverted on the email. Hope to receive your feedback on the same. @AmazonHelp https://t.co/vk6bpEfLdo

================================================================================
EXAMPLE 52
================================================================================
thanks @115821 !! https://t.co/S0ruU15s96

================================================================================
EXAMPLE 53
================================================================================
@Tesco Can i get a digital copy online?

================================================================================
EXAMPLE 54
================================================================================
@AmazonHelp Alright so got another mail - telling me nothing can be done. I have reorder! What will I benefit from your investigation?!

================================================================================
EXAMPLE 55
================================================================================
@115821 Why does my package say delivered but its not here yet?! Tell your drivers to stop lying. 2nd time this has happened!

================================================================================
EXAMPLE 56
================================================================================
@AmazonHelp The last one was £7.99 amazon prime

================================================================================
EXAMPLE 57
================================================================================
@AmazonHelp 感謝感激！

================================================================================
EXAMPLE 58
================================================================================
@115850 I have already done that.

================================================================================
EXAMPLE 59
================================================================================
@AmazonHelp I replied a while ago

================================================================================
EXAMPLE 60
================================================================================
@AmazonHelp It's gotten so I will finish my preorders I've already made. I can shop elsewhere, you treat me like you don't want my business.

================================================================================
EXAMPLE 61
================================================================================
Has anyone else that’s an @115821 prime member noticed that free “2 day” shipping is now consistently more like FIVE day shipping..? Annoyed. @123644 @AmazonHelp

================================================================================
EXAMPLE 62
================================================================================
@115850 Hi Amazon, I was planning to buy Honor Redmi 3 activity tracker model - NYX-B10HN. It's cost was 2,200 INR, but now it has doubled up to 4,399 INR. Can I please get it at 2,200 itself ?
#JustAsking #TryingOutMyLuck #FamousAmazonIndia

================================================================================
EXAMPLE 63
================================================================================
@AmazonHelp Okay... Shall I delete that tweet?

================================================================================
EXAMPLE 64
================================================================================
@AmazonHelp Ordered a gift card last Sunday. 1-Day delivery. Confirmation e-mail said Thursday. Thursday, the date changed to Tuesday. I cancelled.

================================================================================
EXAMPLE 65
================================================================================
@AmazonHelp Justement, j'ai discuté 2 fois avec eux aujourd'hui. et les 2 personnes m'ont assurées que je serais livré ce jour. Vous pouvez regarder les historiques sans problème. Date de livraison garantie.

================================================================================
EXAMPLE 66
================================================================================
@525707 @525706 @Tesco tags his boys in order for likes, pure weapon, on ya bike

================================================================================
EXAMPLE 67
================================================================================
@AmazonHelp My package still hasn’t arrived 😥

================================================================================
EXAMPLE 68
================================================================================
@115830 You robbed money from my bank account and you still haven't responded. You dirty thieves.

================================================================================
EXAMPLE 69
================================================================================
@AmazonHelp Able to take advantage of it as it was taken off 🙁 I spend a lot with amaZon every month. I choose you over other websites because of your

================================================================================
EXAMPLE 70
================================================================================
@AmazonHelp My parcel was supposed to be delivered today and come before 8, where is it? Has just said out for delivery for the entire day 🙄

================================================================================
EXAMPLE 71
================================================================================
@643182 @116313 見てて安らぐ感じが良いですよね(　＾ω＾)
寝る前にはピッタリかも！( ´∀`)

================================================================================
EXAMPLE 72
================================================================================
@AmazonHelp Yup you guys sent the chat's convo script

================================================================================
EXAMPLE 73
================================================================================
omg mon colis est dans un sale état et c'est censé être un disque dur dedans ??

================================================================================
EXAMPLE 74
================================================================================
#AmazonLogistics parece lo peor que le ha pasado a @115821 . Dejen a los expertos en envíos hacer su trabajo.

================================================================================
EXAMPLE 75
================================================================================
@AmazonHelp @115817 @UPSHelp this is not acceptable, you guys kept me waiting all day yesterday and today and now u want me to wait till monday, NO!

================================================================================
EXAMPLE 76
================================================================================
@AmazonHelp 407-1840559-7509101. Product already pick up. But account details doesn't show about return. Because of that I can't able to

================================================================================
EXAMPLE 77
================================================================================
@122596 I am not getting a positive response for the extended warranty... Which is not helpful at all. I purchased this product with this belief

================================================================================
EXAMPLE 78
================================================================================
@120533 payer une version deluxe d'un jeu (payée 30€ de plus) pour être livré en avance, et finalement livré en retard avec 5€ de compensation. Merci Amazon #FoutageDeGueule 👌👌👌

================================================================================
EXAMPLE 79
================================================================================
@Tesco Paying the money to just look at a loading screen....

================================================================================
EXAMPLE 80
================================================================================
@UPSHelp Jetzt wundert mich nicht mehr, warum der werte Bote nicht bei mir klingeln wollte. So ein Paket hätte ich bei mir auch nicht abgeben wollen!!! Wie wird denn hier mit fremdem Eigentum umgegangen? @AmazonHelp Was meint ihr dazu? Das geht letztlich an euch zurück! https://t.co/HlQ1P9t4tM

================================================================================
EXAMPLE 81
================================================================================
Uhhhhh @117634 I accidentally hit buy with one click for a kindle book and y’all won’t let me refund it.

================================================================================
EXAMPLE 82
================================================================================
@115821.com your seller department has been reviewing my husband for 4 weeks now. We want income we are from Puerto Rico!!!

================================================================================
EXAMPLE 83
================================================================================
@Tesco CodWWII

================================================================================
EXAMPLE 84
================================================================================
@AmazonHelp Hice un pedido, a día de hoy no ha llegado, dos llamadas y nada, quiero cancelarlo y no quiero saber nada más, 1 mes esperando. Muy mal

================================================================================
EXAMPLE 85
================================================================================
@AmazonHelp Hi i have a query i live in Marthahalli bridge area (Bengaluru) . can you tell me where is the nearest location for phone exchange ???

================================================================================
EXAMPLE 86
================================================================================
. @AmazonHelp it says you may have lost my package and has no estimated delivery date. My package is almost a month late. 🙄

================================================================================
EXAMPLE 87
================================================================================
@115821 used to surprise me with early deliveries. Now, #amazonprime surprises me if it happens to deliver on time.
What am I paying for?

================================================================================
EXAMPLE 88
================================================================================
@AmazonHelp There were delays of course due to the hurricane, but the post office is working now. I just got one order from September 19.

================================================================================
EXAMPLE 89
================================================================================
@AmazonHelp Nada, todo bien, estoy esperando un paquete. ¡Gracias por preguntar!

================================================================================
EXAMPLE 90
================================================================================
OK, this is enough. Got an email, called them after 5 hours, was told to wait again for 2 days. @115821 I am not giving you a single cent more. No word from @115851 either. Amazing. @AmazonHelp = Pathetic https://t.co/pWwKfTSSUe

================================================================================
EXAMPLE 91
================================================================================
@116316 Is this an international version? https://t.co/yQqX55guvk

================================================================================
EXAMPLE 92
================================================================================
@Tesco Hi, the allies keep winning when I play. Is there any way to change this?

================================================================================
EXAMPLE 93
================================================================================
@115850 when phone is out if stock pls dnt decieve customer...felt humiliation,dnt misguide ur loyal customers https://t.co/zYc3KJep5Q

================================================================================
EXAMPLE 94
================================================================================
Shoutout to @115821 for having my favorite @2647 #hdconcealers at a discounted rate of $3 in the @2647 store and only they $5 #iwin #nyxcosmetics https://t.co/H3Sb0rprXw

================================================================================
EXAMPLE 95
================================================================================
@AmazonHelp Voy ahora de nuevo a pasarme por la oficina de ASM a ver si han encontrado el paquete. Pero que pedir a un locker que está a tres  calles de mi casa haga que el paquete llegue un día antes... Hacéoslo mirar. Tengo todo ahora de 2 a 3 días en domicilio.

================================================================================
EXAMPLE 96
================================================================================
Bearing in mind I preorder this item I got a message saying it’s delayed a week, but the one I bought from Amazon is from the same company?!

================================================================================
EXAMPLE 97
================================================================================
@375097 We are working on this and will get back to you shortly.
Thank you for your patience.

================================================================================
EXAMPLE 98
================================================================================
@479024 @Tesco @479023 Classic 😂

================================================================================
EXAMPLE 99
================================================================================
@Tesco I paid £2 more...two cheeseburgers there 👀

================================================================================
EXAMPLE 100
================================================================================
@AmazonHelp Due to GST every state have same MRP now and this product is manufactured after GST how you can charge more than MRP explain this or I will go to the consumer court

In [ ]:
for i, row in intent_examples.iloc[100:150].iterrows():

    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 1}")
    print("=" * 80)
    print(row["text"])

================================================================================
EXAMPLE 101
================================================================================
@115850
For some reason Amazon India follows a special clock where there 24hrs have not got over since 9th October !! Pathetic service and height of arrogance !! False promises and cheaters !!
#Cheaters #FalsePromises

================================================================================
EXAMPLE 102
================================================================================
@AmazonHelp @AmazonHelp any news on this? The other cd i pre-ordered at the same time has now come but this was only released friday. This item has had over a week to arrive

================================================================================
EXAMPLE 103
================================================================================
@119038 @115821 cancelled auto-renew of prime which expires December 19 but my Twitch prime is no longer being accepted. Can't get rewards even though my account is technically active.

================================================================================
EXAMPLE 104
================================================================================
@616488 @AmazonHelp Everything stopped working (delivery wise) about 2 months ago. Before, service worked flawlessly. Now, pretty much guaranteed a next-day delivery won't arrive as expected in 24hrs. It's ridiculous. No way to follow up on complaints either.

================================================================================
EXAMPLE 105
================================================================================
@AmazonHelp Yes I do. Now humbly waiting for call.

================================================================================
EXAMPLE 106
================================================================================
@116928 pésimo servicio, nunca más. Desde el día 6 esperando, quedan de llamarme para anular el pedido y nada. #Verguenza

================================================================================
EXAMPLE 107
================================================================================
yo @115821 USPS has a better shipping service than AMZL US. At least they attempt to put my shit inside the screen door or the mailbox. smh

================================================================================
EXAMPLE 108
================================================================================
@AmazonHelp Pouvez-vous faire une vérification ? S'il vous plaît ?

================================================================================
EXAMPLE 109
================================================================================
@AmazonHelp I’ve said, nothing has been received!

================================================================================
EXAMPLE 110
================================================================================
@AmazonHelp No such social media emails received from your end

================================================================================
EXAMPLE 111
================================================================================
@AmazonHelp Submitted one now with complete day to day description of issues. 5 days of irritating service with no outcome!

================================================================================
EXAMPLE 112
================================================================================
@AmazonHelp I am on the delivery page right now if u can provide me nearest location it will b very helpful

================================================================================
EXAMPLE 113
================================================================================
@391454 @AmazonHelp @403032 Just saying send DM but they are Never Again called and text ,

================================================================================
EXAMPLE 114
================================================================================
@AmazonHelp go back you care and told them Pls talk to my on my cell 9478564440

================================================================================
EXAMPLE 115
================================================================================
@Tesco Nevermind, just realised the disk is inside the case.

================================================================================
EXAMPLE 116
================================================================================
He pedido un juego a @115821 que nos tenía que llegar a la cafetería donde estamos siempre abiertos, hemos mirado en @4496 y nos dicen que lo han entregado pero a nosotros no nos lo ha dado nadie... Me encantaría saber que ha pasado... O si es un timo...

================================================================================
EXAMPLE 117
================================================================================
@Tesco Has call of duty ww2 ran out of stock in all shops?

================================================================================
EXAMPLE 118
================================================================================
@AmazonHelp #fakepromises,Still no replies &amp; no product delivery.😡
#Neverending wait

================================================================================
EXAMPLE 119
================================================================================
@AmazonHelp I am tired @115850  @AmazonHelp. I have been asking you to resolve this issue over a month and you are constantly delaying it #amazonsucks

================================================================================
EXAMPLE 120
================================================================================
@414951 @115830 I was fine with the day that was on the order confirmation AND the dispatch notification…but then it changed to another day the next morning - that’s my problem :)

================================================================================
EXAMPLE 121
================================================================================
Wtf @115821 thx for delivering my package https://t.co/L1rUNYSqJW

================================================================================
EXAMPLE 122
================================================================================
@122596 Thanks alot for taking care of my query. @AmazonHelp  it is sorted.

================================================================================
EXAMPLE 123
================================================================================
@AmazonHelp I know. I've emailed it and you guys have taken care of it. Some people would get tricked but not me. I know how to Internet

================================================================================
EXAMPLE 124
================================================================================
@AmazonHelp i am struggling to get 1 TV , in 1 month from amazon. 2 time .

================================================================================
EXAMPLE 125
================================================================================
@116875 pésimo servicio d entrega, 1paquet q tuvo q llegar DESDE ayer, y a esta hora TODAVÍA NOO LLEGA y pague envío 😡😡😡😡

================================================================================
EXAMPLE 126
================================================================================
@119625 #ERROR  unable to subscribe amazon prime video from amazon prime android app... After click join prime show this empty page https://t.co/4AsaLRPYne

================================================================================
EXAMPLE 127
================================================================================
@AmazonHelp Nothing. They just told me to wait until Monday, which is unacceptable. They claim nothing can be done. It needs to be delivered today, or there's no point in delivering it, at all.

================================================================================
EXAMPLE 128
================================================================================
@Tesco I just paid £55 pound for this game because most Tesco’s In the UK haven’t even got the game on sale

================================================================================
EXAMPLE 129
================================================================================
@AmazonHelp MD-PAYBAL is the sender of this sms. site under reference is https://t.co/7XwBacsMqO  . Please check ?

================================================================================
EXAMPLE 130
================================================================================
@AmazonHelp @AmazonHelp - kindly elaborate on the problem that U r working on !! I don't wanna hear that U will need another 24hrs to respond in case U r working on a wrong problem !!

================================================================================
EXAMPLE 131
================================================================================
@AmazonHelp Thanks... I have tried everything and been I. The phone several times and nothing has worked so far!!

================================================================================
EXAMPLE 132
================================================================================
@Tesco Any ideas when this could be?

================================================================================
EXAMPLE 133
================================================================================
@119076 @115817 Had this happen before. You can get it from their Customer Care Center: 8440 Ardwick Ardmore Rd Landover, MD 20785

================================================================================
EXAMPLE 134
================================================================================
@AmazonHelp where the fuck is my package

================================================================================
EXAMPLE 135
================================================================================
@AmazonHelp From audible

================================================================================
EXAMPLE 136
================================================================================
@AmazonHelp Still i dnt get my refund why

================================================================================
EXAMPLE 137
================================================================================
@Tesco Would be great if you could actually tell me what happened to mine that I ordered. Taking hours to reply to me on dm's.

================================================================================
EXAMPLE 138
================================================================================
@115850 the worlds pathatic delivery from amazon i wont expect this thing from you
My order no is 237280295936 i want my product today

================================================================================
EXAMPLE 139
================================================================================
アマゾンがプリパラのBDBOXと3dsゲームの支払い番号を送ってこないんじゃが…

================================================================================
EXAMPLE 140
================================================================================
@AmazonHelp Je l'ai déjà fais ...

================================================================================
EXAMPLE 141
================================================================================
@AmazonHelp Hi, I've returned an item to @116316 13 days ago and haven't heard anything since. 'Tracking info not available' it says..

================================================================================
EXAMPLE 142
================================================================================
Hey @115830 is there an issue with checking out?? Keep trying to complete my order of 12 items and it won’t let me get past delivery options page. Getting very irritated.

================================================================================
EXAMPLE 143
================================================================================
No football tonight, just family. #TNFonPrimeVideo returns on 11/30. https://t.co/xmN9TtIVHK

================================================================================
EXAMPLE 144
================================================================================
@AmazonHelp that I can't get my order adjusted at all. /3

================================================================================
EXAMPLE 145
================================================================================
@AmazonHelp Ordered CoD game in Sept, didn't arrive today. Reordered another for next day delivery tomorrow. It's now delayed too. Very frustrated.

================================================================================
EXAMPLE 146
================================================================================
@115830 just been notified that my package has been delivered to my neighbour Jim at number 6, I’ve been in all day, there isn’t a number 6, none of my neighbours are called Jim. SO TELL ME WHERE MY BLOODY ORDER IS!!!

================================================================================
EXAMPLE 147
================================================================================
@AmazonHelp I am going to guess those tokens were supposed to be the confirmation. ;)

================================================================================
EXAMPLE 148
================================================================================
@AmazonHelp I have sent them an email. There response was there is no a/c under my email. But all the reset codes are coming through to it. So did someone cancel my a/c?

================================================================================
EXAMPLE 149
================================================================================
@AmazonHelp Please deliver my order now ASAP I wanted gift  someone do this that we will continue same if anything happens to me Amazon will responsible...  Because I never seen Angy and badass delivery boy screaming on phone abusing the costumer

================================================================================
EXAMPLE 150
================================================================================
so my parcel from @115821 says it’s been delivered to me for the last hour now n it’s still not here:(

In [ ]:
for i, row in intent_examples.iloc[150:200].iterrows():

    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 1}")
    print("=" * 80)
    print(row["text"])

================================================================================
EXAMPLE 151
================================================================================
@AmazonHelp I was only given the option to return but I want more done. This was supposed to be a gift for some one but it first arrived late, then damaged. Then the replacement was damaged as well.

================================================================================
EXAMPLE 152
================================================================================
@AmazonHelp Please read the reply they want information from you... @AmazonHelp  @115850 https://t.co/XNK3bVq1Hx

================================================================================
EXAMPLE 153
================================================================================
@AmazonHelp i managed to edit/delete them by logging in from my phone, thanks for the advice

================================================================================
EXAMPLE 154
================================================================================
@AmazonHelp This Item to the Netherlands https://t.co/JvKd1Rl3FG

================================================================================
EXAMPLE 155
================================================================================
@AmazonHelp I like dat attitude &amp; it wil giv yu long mileage. Service is indeed the backbone of any company which will decide it's success or demise.

================================================================================
EXAMPLE 156
================================================================================
@AmazonHelp Merci pour votre aide et celles de vos collègues du site @120533 qui ont fait une remontée d'informations à BPOST qui a livré mon colis aujourd'hui.

================================================================================
EXAMPLE 157
================================================================================
@AmazonHelp this is ridiculous. Read the comments. This retailer is literally STEALING from us. DO SOMETHING. https://t.co/vvWkvOCeVF

================================================================================
EXAMPLE 158
================================================================================
@AmazonHelp How much more days to return my product @115850 ? Can you deliver it to proper address now !

================================================================================
EXAMPLE 159
================================================================================
@AmazonHelp I've placed both my return items in the same box, that's how I got them. Is that ok? I placed the return form for both inside.

================================================================================
EXAMPLE 160
================================================================================
#HearUsAmazon

Fed up with garbage returns / No Track on our returns @115850 @115851 @128876 https://t.co/DgIvsmyaKT

================================================================================
EXAMPLE 161
================================================================================
C’est mal de laisser un calque mal synchronisé sur une pub @AmazonHelp https://t.co/zoitAPvFNZ

================================================================================
EXAMPLE 162
================================================================================
@AmazonHelp あ、わかりましたありがとうございました！

================================================================================
EXAMPLE 163
================================================================================
@AmazonHelp Today was the original delivery date. It's a prime shipping order.  I believe UPS has it in Omaha.

================================================================================
EXAMPLE 164
================================================================================
@AmazonHelp going to have to stop using u. Fed up of my deliveries going to someone else’s house. Seems your courier can’t read road signs

================================================================================
EXAMPLE 165
================================================================================
Be aware Amazon Pay is a one way street, they will let you add money to it but not let you take it out unlike other competing wallets. A further irritant is that such monies should he used for purchase within 1 year failing which one forefits it. #baddeal

@115850

================================================================================
EXAMPLE 166
================================================================================
@115850 I haven’t got the cash back when I used SBI card on 17th

================================================================================
EXAMPLE 167
================================================================================
@115821 been online with customer service chat for over an hour because the delivery status says delivered to resident but was not handed to anyone who lives in this apt and all we want is a refund. Why is this such an issue right now????

================================================================================
EXAMPLE 168
================================================================================
@Tesco I would love to buy this game but it’s old out every Tesco’s near me 😞😡

================================================================================
EXAMPLE 169
================================================================================
@AmazonHelp No worries! It was delivered on time. Just to my next door neighbors house :( not your fault

================================================================================
EXAMPLE 170
================================================================================
My mom melted my fire stick remote don’t ask me how cause I’m still trying to figure out too 🙃

================================================================================
EXAMPLE 171
================================================================================
@AmazonHelp Questioned The Neighbors &amp; All My Relatives . We Did Receive A Package That Day But 2 Were Missing Only One Received

================================================================================
EXAMPLE 172
================================================================================
@Tesco @494961 Stacey just absolutely mugged Ellis. Free drinks on me

================================================================================
EXAMPLE 173
================================================================================
@AmazonHelp @130687 Estamos en ello, pero sé lo que ocurre, que con @80 jamás nos llegan los pedidos el día que tienen que llegar. Da igual lo que sea, pero jamás llegan cuando tocan. Un pedido tardó más de una semana. Y no pasa nada, claro.

================================================================================
EXAMPLE 174
================================================================================
@AmazonHelp Y que me dices a esto?  Se supone que hoy debería llegar!! https://t.co/p6hmRBu6Kp

================================================================================
EXAMPLE 175
================================================================================
@AmazonHelp Delivery was fine with FedEx and USPS. Probably because those drivers knew the area. Train Flex drivers to be more determined.

================================================================================
EXAMPLE 176
================================================================================
@AmazonHelp eu to namorando esse kindle paperwhite faz teeeeempo! To tomando coragem pra adquirir haha

================================================================================
EXAMPLE 177
================================================================================
@525697 @Tesco You know their customer service cares when every message is from a different person

================================================================================
EXAMPLE 178
================================================================================
@116313 チャットが繋がりませんが障害が発生しているのですか？

================================================================================
EXAMPLE 179
================================================================================
@AmazonHelp Actually, I’ve done one better and contacted UPS. The told me AMAZON is the problem. You didn’t get them the package on time. So...

================================================================================
EXAMPLE 180
================================================================================
So, uh... On Saturday I ordered some spatulas from @115821 and they were scheduled for delivery to an Amazon locker on Monday (today).
Yesterday I got an email saying they couldn't deliver and I may need to provide a security code.

================================================================================
EXAMPLE 181
================================================================================
@AmazonHelp Hi, I called into customer care just now to correct an incorrect shipping address, and then the rep told me my account was compromised and locked me out. I can’t change my PW, or login and I can’t correct the shipping address. Help???

================================================================================
EXAMPLE 182
================================================================================
@AmazonHelp On 6th I gt a email, tht 2 make situatn rt Im gtn rplcmnt, 4 which I alrdy paid. I didn't gt a explntn fr the delay or fr nt gtn rglr updts.

================================================================================
EXAMPLE 183
================================================================================
@119625 #amazonprimefail #servicedown https://t.co/GFcazUmZzF

================================================================================
EXAMPLE 184
================================================================================
@AmazonHelp @123967 Why do you even bother giving tracking information for Sunday deliveries if it is not even going to be delivered then?

================================================================================
EXAMPLE 185
================================================================================
@AmazonHelp Amazon shipping

================================================================================
EXAMPLE 186
================================================================================
@AmazonHelp いえいえ

================================================================================
EXAMPLE 187
================================================================================
@AmazonHelp Hey, got my item delivered sometime ago. Thank you :)

================================================================================
EXAMPLE 188
================================================================================
@115821 once again @3375 was chosen as a carrier for delivering a package I ordered, and this is how I find it when I get home. The package appears to have been opened and then resealed. Please stop using this carrier. https://t.co/EiIQnYBuPA

================================================================================
EXAMPLE 189
================================================================================
@Tesco Yes. Expensive to let it go n not get a refund on a game u don’t like that’s all for him only owning it a day. Nevermind

================================================================================
EXAMPLE 190
================================================================================
@119625 @12327 we are all waiting for its second episode. don't when @119625 is droping this.

================================================================================
EXAMPLE 191
================================================================================
@AmazonHelp Que faire si ma commande est suspendu alors que je dois la recevoir pour demain ?(Amazon prime )

================================================================================
EXAMPLE 192
================================================================================
@AmazonHelp Erst sieht's so aus. https://t.co/DjpsdPhVY7

================================================================================
EXAMPLE 193
================================================================================
@115830 @AmazonHelp Please tell me why I ordered a shirt using Prime to get here on Friday and I still don't have it? My flats office is..

================================================================================
EXAMPLE 194
================================================================================
@AmazonHelp @115851 Why you can't? If you are going to turn down your regular customer like this. I don't see any option then stop using your services.

================================================================================
EXAMPLE 195
================================================================================
@Tesco Is it true yer get 3 months xbox live when you purchase cod ww2 at tesco  ?

================================================================================
EXAMPLE 196
================================================================================
@Tesco @374104 Oh Tesco, you're so silly. @141503

================================================================================
EXAMPLE 197
================================================================================
@Tesco It was COD WWll

================================================================================
EXAMPLE 198
================================================================================
Amazon's FBA is a great way to lose money, all season long! Every time I sell something, it goes into the red, and they snatch more money from my credit card. #amazon #FBA @115821

================================================================================
EXAMPLE 199
================================================================================
@AmazonHelp @115850 you owe my 2500 rs as you forcibly refunded me in Amazon Pay despite taking bank details.Cant succumb to ur autocracy.

================================================================================
EXAMPLE 200
================================================================================
@115850 @AmazonHelp I have already shared my details but you lie in order to refuse the cashback.

In [ ]:
import re
from collections import Counter

# Combine the 200 customer messages
texts = intent_examples["text"].fillna("").astype(str).tolist()

all_text = " ".join(texts).lower()

keywords = [
    "delivery",
    "delivered",
    "package",
    "parcel",
    "order",
    "refund",
    "return",
    "cashback",
    "prime",
    "payment",
    "charged",
    "charge",
    "account",
    "login",
    "password",
    "app",
    "product",
    "item",
    "damaged",
    "broken",
    "cancel",
    "customer service",
    "complaint"
]

keyword_counts = {}

for keyword in keywords:
    keyword_counts[keyword] = all_text.count(keyword)

keyword_counts

{'delivery': 23,
 'delivered': 14,
 'package': 12,
 'parcel': 2,
 'order': 28,
 'refund': 8,
 'return': 9,
 'cashback': 1,
 'prime': 19,
 'payment': 0,
 'charged': 0,
 'charge': 3,
 'account': 7,
 'login': 1,
 'password': 0,
 'app': 9,
 'product': 6,
 'item': 7,
 'damaged': 2,
 'broken': 0,
 'cancel': 7,
 'customer service': 2,
 'complaint': 1}

In [ ]:
keyword_df = (
    pd.DataFrame(
        keyword_counts.items(),
        columns=["keyword", "count"]
    )
    .sort_values("count", ascending=False)
)

keyword_df

             keyword  count
4              order     28
0           delivery     23
8              prime     19
1          delivered     14
2            package     12
15               app      9
6             return      9
5             refund      8
20            cancel      7
17              item      7
12           account      7
16           product      6
11            charge      3
3             parcel      2
18           damaged      2
21  customer service      2
7           cashback      1
22         complaint      1
13             login      1
14          password      0
10           charged      0
9            payment      0
19            broken      0

In [ ]:
delivery_examples = intent_examples[
    intent_examples["text"].str.contains(
        r"delivery|delivered|package|parcel|shipping|arriv",
        case=False,
        na=False
    )
]

print("Delivery-related examples:", len(delivery_examples))

for _, row in delivery_examples.head(20).iterrows():
    print("\n---")
    print(row["text"])

Delivery-related examples: 43

---
@115850 Called the Amazon delivery agent, he told me it was cancelled and in my order detail. Why does it says I cancelled it ?M I goin 2 get d phn?

---
@115821 @AmazonHelp thanks to ur driver 2day my bf n I lost out on our #snes bc they didn't use the locker but "delivered" them somewhere

---
@AmazonHelp It was your delivery person. AMZL US

---
@115850 @115821 Sir its 10-13 oct but I booked the SD memory card yesterday can u pls pls arrange asap delivery of my order.

---
Way to go @115821! You keep making promises you can’t keep.
You promise two day shipping: Doesn’t Show. (you lost it)
You promise you’ll cover the cost of one day shipping: Not Available.
Last promise is to refund my money: TBD

---
@AmazonHelp First delivery which was placed in AUGUST, still says dispatched. And second order says out for delivery has been like this for 3 days and I paid £5.99 for next day?

---
@AmazonHelp Delivery wise, what's the difference between getting something delivered home and getting something delivered to work?

---
@115850 @AmazonHelp Issues in delivery for past 4 packages, same repeats for reverse pickup.

---
@AmazonHelp No, phoned you 5 times over  last 2 weeks(diff orders-same issue) yesterday a supervisor promised redelivery today. Just NOW got delay msg!

---
@AmazonHelp so it’s “delivered” - I call Immediately to say it hasn’t been delivered &amp; CSR says to “wait a day”! 👌🏻🙄 #PrimeMemberForWhat https://t.co/GipMNRIWMw

---
@115821 Why does my package say delivered but its not here yet?! Tell your drivers to stop lying. 2nd time this has happened!

---
Has anyone else that’s an @115821 prime member noticed that free “2 day” shipping is now consistently more like FIVE day shipping..? Annoyed. @123644 @AmazonHelp

---
@AmazonHelp Ordered a gift card last Sunday. 1-Day delivery. Confirmation e-mail said Thursday. Thursday, the date changed to Tuesday. I cancelled.

---
@AmazonHelp My package still hasn’t arrived 😥

---
@AmazonHelp My parcel was supposed to be delivered today and come before 8, where is it? Has just said out for delivery for the entire day 🙄

---
. @AmazonHelp it says you may have lost my package and has no estimated delivery date. My package is almost a month late. 🙄

---
@AmazonHelp @AmazonHelp any news on this? The other cd i pre-ordered at the same time has now come but this was only released friday. This item has had over a week to arrive

---
@616488 @AmazonHelp Everything stopped working (delivery wise) about 2 months ago. Before, service worked flawlessly. Now, pretty much guaranteed a next-day delivery won't arrive as expected in 24hrs. It's ridiculous. No way to follow up on complaints either.

---
yo @115821 USPS has a better shipping service than AMZL US. At least they attempt to put my shit inside the screen door or the mailbox. smh

---
@AmazonHelp I am on the delivery page right now if u can provide me nearest location it will b very helpful

In [ ]:
refund_examples = intent_examples[
    intent_examples["text"].str.contains(
        r"refund|return|money back",
        case=False,
        na=False
    )
]

print("Refund/return examples:", len(refund_examples))

for _, row in refund_examples.head(20).iterrows():
    print("\n---")
    print(row["text"])

Refund/return examples: 15

---
@AmazonHelp 408-7381410-8288305 refund not yet given amazon must pay panality as 5 days passed for amount ₹699

---
@AmazonHelp Okay, it has been three business days, but you've already processed the refund, so thanks.

---
Way to go @115821! You keep making promises you can’t keep.
You promise two day shipping: Doesn’t Show. (you lost it)
You promise you’ll cover the cost of one day shipping: Not Available.
Last promise is to refund my money: TBD

---
@AmazonHelp 407-1840559-7509101. Product already pick up. But account details doesn't show about return. Because of that I can't able to

---
Uhhhhh @117634 I accidentally hit buy with one click for a kindle book and y’all won’t let me refund it.

---
@AmazonHelp Still i dnt get my refund why

---
@AmazonHelp Hi, I've returned an item to @116316 13 days ago and haven't heard anything since. 'Tracking info not available' it says..

---
No football tonight, just family. #TNFonPrimeVideo returns on 11/30. https://t.co/xmN9TtIVHK

---
@AmazonHelp I was only given the option to return but I want more done. This was supposed to be a gift for some one but it first arrived late, then damaged. Then the replacement was damaged as well.

---
@AmazonHelp How much more days to return my product @115850 ? Can you deliver it to proper address now !

---
@AmazonHelp I've placed both my return items in the same box, that's how I got them. Is that ok? I placed the return form for both inside.

---
#HearUsAmazon

Fed up with garbage returns / No Track on our returns @115850 @115851 @128876 https://t.co/DgIvsmyaKT

---
@115821 been online with customer service chat for over an hour because the delivery status says delivered to resident but was not handed to anyone who lives in this apt and all we want is a refund. Why is this such an issue right now????

---
@Tesco Yes. Expensive to let it go n not get a refund on a game u don’t like that’s all for him only owning it a day. Nevermind

---
@AmazonHelp @115850 you owe my 2500 rs as you forcibly refunded me in Amazon Pay despite taking bank details.Cant succumb to ur autocracy.

In [ ]:
prime_examples = intent_examples[
    intent_examples["text"].str.contains(
        r"prime|twitch",
        case=False,
        na=False
    )
]

print("Prime-related examples:", len(prime_examples))

for _, row in prime_examples.head(20).iterrows():
    print("\n---")
    print(row["text"])

Prime-related examples: 14

---
@116316  Hallo, wieso steht beim Prime Versand bei euch ein Liefertermin am Dienstag 28.11.17 wenn man jetzt bestellt. Ich bin Prime Kunde. Danke und Gruß

---
@AmazonHelp Besides, I no longer want an account with Amazon. Keep it frozen for all I care, or destroy it. All I'm asking is that you not charge me for prime on an account which you have frozen.

---
@AmazonHelp Another prime fail!
I really don’t know what I pay for your absolute dire service! I wouldn’t recommend anyone to prime!
#fail https://t.co/e5x4LgAXr4

---
@AmazonHelp so it’s “delivered” - I call Immediately to say it hasn’t been delivered &amp; CSR says to “wait a day”! 👌🏻🙄 #PrimeMemberForWhat https://t.co/GipMNRIWMw

---
@AmazonHelp The last one was £7.99 amazon prime

---
Has anyone else that’s an @115821 prime member noticed that free “2 day” shipping is now consistently more like FIVE day shipping..? Annoyed. @123644 @AmazonHelp

---
@115821 used to surprise me with early deliveries. Now, #amazonprime surprises me if it happens to deliver on time.
What am I paying for?

---
@119038 @115821 cancelled auto-renew of prime which expires December 19 but my Twitch prime is no longer being accepted. Can't get rewards even though my account is technically active.

---
@119625 #ERROR  unable to subscribe amazon prime video from amazon prime android app... After click join prime show this empty page https://t.co/4AsaLRPYne

---
No football tonight, just family. #TNFonPrimeVideo returns on 11/30. https://t.co/xmN9TtIVHK

---
@AmazonHelp Today was the original delivery date. It's a prime shipping order.  I believe UPS has it in Omaha.

---
@119625 #amazonprimefail #servicedown https://t.co/GFcazUmZzF

---
@AmazonHelp Que faire si ma commande est suspendu alors que je dois la recevoir pour demain ?(Amazon prime )

---
@115830 @AmazonHelp Please tell me why I ordered a shirt using Prime to get here on Friday and I still don't have it? My flats office is..

In [ ]:
INTENTS = {
    "delivery_issue": {
        "description": "Problems with delivery, shipping, delayed packages, missing packages, or incorrect delivery."
    },
    
    "order_management": {
        "description": "Requests to cancel, modify, change, or manage an existing order."
    },
    
    "return_refund": {
        "description": "Requests or problems involving product returns, refunds, or money being returned."
    },
    
    "product_issue": {
        "description": "Problems with a product such as damaged, defective, broken, or incorrect items."
    },
    
    "payment_billing": {
        "description": "Payment failures, unexpected charges, duplicate charges, billing, or payment-related problems."
    },
    
    "prime_membership": {
        "description": "Problems or questions about Amazon Prime, Prime benefits, membership, or Twitch Prime."
    },
    
    "account_access": {
        "description": "Problems accessing, logging into, or managing an Amazon account."
    },
    
    "technical_issue": {
        "description": "Problems with the Amazon website, app, technical functionality, or device/software behavior."
    },
    
    "customer_complaint": {
        "description": "Complaints about customer service, poor treatment, frustration, or requests for escalation without another dominant operational issue."
    },
    
    "other_unclear": {
        "description": "Messages that do not fit another intent, are too vague, contain only thanks/acknowledgement, or lack enough information."
    }
}

print("Number of intents:", len(INTENTS))

for name, info in INTENTS.items():
    print(f"\n{name}")
    print(info["description"])

Number of intents: 10

delivery_issue
Problems with delivery, shipping, delayed packages, missing packages, or incorrect delivery.

order_management
Requests to cancel, modify, change, or manage an existing order.

return_refund
Requests or problems involving product returns, refunds, or money being returned.

product_issue
Problems with a product such as damaged, defective, broken, or incorrect items.

payment_billing
Payment failures, unexpected charges, duplicate charges, billing, or payment-related problems.

prime_membership
Problems or questions about Amazon Prime, Prime benefits, membership, or Twitch Prime.

account_access
Problems accessing, logging into, or managing an Amazon account.

technical_issue
Problems with the Amazon website, app, technical functionality, or device/software behavior.

customer_complaint
Complaints about customer service, poor treatment, frustration, or requests for escalation without another dominant operational issue.

other_unclear
Messages that do not fit another intent, are too vague, contain only thanks/acknowledgement, or lack enough information.

In [ ]:
INTENT_RULES = """
Classify based on the customer's primary support need.

Important rules:

1. Delivery problems take priority when the main issue is a package being late,
   missing, delivered incorrectly, or not received.

2. Order management is for changing/cancelling an order, not general delivery
   problems.

3. Return/refund is for returning an item or receiving/refunding money.

4. Product issue is for damaged, defective, broken, or wrong products.

5. Payment/billing is for charges, payment failures, duplicate charges,
   or billing problems.

6. Prime membership is for Prime/Twitch Prime membership or benefits.

7. Account access is for login, password, or account access problems.

8. Technical issue is for Amazon app/website/technical functionality problems.

9. Customer complaint is used when the main purpose is complaining about
   service or requesting escalation and there is no more specific operational
   issue.

10. Other/unclear is used for vague messages, acknowledgements, thanks,
    irrelevant messages, or messages where the intent cannot be determined.
"""

print(INTENT_RULES)

Classify based on the customer's primary support need.

Important rules:

1. Delivery problems take priority when the main issue is a package being late,
   missing, delivered incorrectly, or not received.

2. Order management is for changing/cancelling an order, not general delivery
   problems.

3. Return/refund is for returning an item or receiving/refunding money.

4. Product issue is for damaged, defective, broken, or wrong products.

5. Payment/billing is for charges, payment failures, duplicate charges,
   or billing problems.

6. Prime membership is for Prime/Twitch Prime membership or benefits.

7. Account access is for login, password, or account access problems.

8. Technical issue is for Amazon app/website/technical functionality problems.

9. Customer complaint is used when the main purpose is complaining about
   service or requesting escalation and there is no more specific operational
   issue.

10. Other/unclear is used for vague messages, acknowledgements, thanks,
    irrelevant messages, or messages where the intent cannot be determined.

In [ ]:
intent_keywords = {
    "delivery_issue": r"delivery|delivered|package|parcel|shipping|shipment|driver|carrier|arriv",
    
    "order_management": r"order|cancel|cancellation|cancelled|modify|change",
    
    "return_refund": r"refund|return|money back|reimburse",
    
    "product_issue": r"damaged|damage|broken|defective|wrong item|wrong product",
    
    "payment_billing": r"payment|paid|charge|charged|billing|cashback|debit|credit",
    
    "prime_membership": r"prime|twitch",
    
    "account_access": r"account|login|log in|password|sign in",
    
    "technical_issue": r"app|website|site|error|bug|not working|technical",
    
    "customer_complaint": r"complaint|complain|terrible|pathetic|awful|poor service|escalat",
}

In [ ]:
intent_keyword_counts = {}

for intent, pattern in intent_keywords.items():

    count = intent_examples["text"].str.contains(
        pattern,
        case=False,
        na=False,
        regex=True
    ).sum()

    intent_keyword_counts[intent] = count

intent_keyword_df = (
    pd.DataFrame(
        intent_keyword_counts.items(),
        columns=["intent", "keyword_matches"]
    )
    .sort_values(
        "keyword_matches",
        ascending=False
    )
)

intent_keyword_df

               intent  keyword_matches
0      delivery_issue               45
1    order_management               32
2       return_refund               15
5    prime_membership               14
7     technical_issue               12
4     payment_billing               10
6      account_access                6
8  customer_complaint                5
3       product_issue                1

In [ ]:
def show_conversation(conversation_id):

    conversation = amazon_clean[
        amazon_clean["conversation_id"] == conversation_id
    ].sort_values("created_at")

    print("=" * 80)
    print("CONVERSATION:", conversation_id)
    print("=" * 80)

    for _, row in conversation.iterrows():

        speaker = (
            "CUSTOMER"
            if row["inbound"]
            else "AMAZONHELP"
        )

        print(f"\n[{speaker}]")
        print(row["text"])

In [ ]:
show_conversation(271913)

================================================================================
CONVERSATION: 271913
================================================================================

[CUSTOMER]
@115821 Again?!? PLEASE teach your delivery people the proper way to deliver a package! 2nd time in a week that we have had a poor delivery! https://t.co/eMlPDgA4e8

[AMAZONHELP]
@180886 I'm sorry your package was delivered like this! To confirm, which carrier was assigned: https://t.co/Y5jpI9gRhE? ^MV

[CUSTOMER]
@AmazonHelp Carrier: AMZL US

[AMAZONHELP]
@180886 We'd like to make sure this is reported and investigated. Please send us your info here: https://t.co/I9lbbXc3Wq ^AM

[CUSTOMER]
@AmazonHelp Sent. Thank you for your reply.

[AMAZONHELP]
@180886 Thanks for keeping us in the loop! We'll be in contact soon.  ^AG

[CUSTOMER]
@AmazonHelp BTW this is how the first package, that was delivered to the door, arrived! 😡😡😡 https://t.co/0Y9LdDv1y5

In [ ]:
# Create one representative customer message per AmazonHelp conversation

customer_messages = amazon_clean[
    amazon_clean["inbound"] == True
].copy()

customer_messages = customer_messages.sort_values(
    ["conversation_id", "created_at"]
)

# First customer message in each conversation
first_customer_messages = (
    customer_messages
    .groupby("conversation_id")
    .first()
    .reset_index()
)

print("Total candidate conversations:",
      len(first_customer_messages))

print("\nSample:")
print(
    first_customer_messages[
        ["conversation_id", "text"]
    ].head(10)
)

Total candidate conversations: 82534

Sample:
   conversation_id  \
0            272.0
1            325.0
2            617.0
3            621.0
4            624.0
5            630.0
6            632.0
7            634.0
8            636.0
9            643.0

                                                                                                                                     text
0                                                                                                                amazonのfireTVstickが見れない😢
1                                                                                                                amazonプライムビデオ、再生エラーが多いです
2                                                                   Way to drop the ball on customer service @115821 so pissed right now!
3                                                                        @115823 I want my amazon payments account CLOSED.  dm me please.
4                                  @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?
5      PLAYERUNKNOWN'S BATTLEGROUNDS is now available for preorder on Xbox One consoles - https://t.co/bqLHcBDqAb https://t.co/muLIqeHq0o
6   @115830 my package was ‘accidentally’ opened.. 4 items missing worth £97.\nYou need better delivery drivers!! https://t.co/f6SaVBSMqM
7  @115821 @AmazonHelp why is my order at my local courier for the last 6 days and still hasn’t been delivered to me?? Over 1 week late 😡
8                                  Thanks for the style advice, @115833 look ...I think? #Halloween2017 #flamingo https://t.co/XvI54La043
9                            Bought an @115821 Echo Show and it won’t recognize a single @AmazonHelp account in our household. WTF, guys?

In [ ]:
first_customer_messages["message_length"] = (
    first_customer_messages["text"]
    .fillna("")
    .str.len()
)

print(
    first_customer_messages["message_length"].describe()
)

count    82534.000000
mean       124.627051
std         56.020355
min          6.000000
25%         87.000000
50%        125.000000
75%        144.000000
max        323.000000
Name: message_length, dtype: float64

In [ ]:
# Calculate number of messages in each conversation

conversation_lengths = (
    amazon_clean
    .groupby("conversation_id")
    .size()
    .reset_index(name="conversation_length")
)

# Add conversation length to our candidate dataset

first_customer_messages = first_customer_messages.merge(
    conversation_lengths,
    on="conversation_id",
    how="left"
)

print(first_customer_messages.head())
print("\nConversation length statistics:")
print(first_customer_messages["conversation_length"].describe())

   conversation_id  tweet_id author_id  inbound                created_at  \
0            272.0       272    115770     True 2017-11-22 09:14:39+00:00
1            325.0       325    115792     True 2017-11-22 08:55:35+00:00
2            617.0       617    115820     True 2017-10-31 22:16:32+00:00
3            621.0       621    115822     True 2017-10-31 22:19:34+00:00
4            624.0       624    115824     True 2017-10-31 22:12:37+00:00

                                                                                                     text  \
0                                                                                amazonのfireTVstickが見れない😢
1                                                                                amazonプライムビデオ、再生エラーが多いです
2                                   Way to drop the ball on customer service @115821 so pissed right now!
3                                        @115823 I want my amazon payments account CLOSED.  dm me please.
4  @115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?

  response_tweet_id  in_response_to_tweet_id  message_length  \
0               269                    269.0              24
1               324                      NaN              24
2               615                    615.0              69
3               620                      NaN              64
4               622                    622.0             102

   conversation_length
0                    7
1                    2
2                    5
3                    2
4                    4

Conversation length statistics:
count    82534.000000
mean         4.531975
std          5.322001
min          2.000000
25%          2.000000
50%          3.000000
75%          5.000000
max        448.000000
Name: conversation_length, dtype: float64

In [ ]:
# Clean candidate messages

candidates = first_customer_messages.copy()

candidates["text"] = candidates["text"].fillna("").astype(str)

# Remove empty messages
candidates = candidates[
    candidates["text"].str.strip().str.len() >= 10
].copy()

print("Usable candidates:", len(candidates))

print("\nMessage length:")
print(candidates["message_length"].describe())

Usable candidates: 82509

Message length:
count    82509.000000
mean       124.662485
std         55.991834
min         10.000000
25%         87.000000
50%        125.000000
75%        144.000000
max        323.000000
Name: message_length, dtype: float64

In [ ]:
# Message-length groups

candidates["message_length_group"] = pd.cut(
    candidates["message_length"],
    bins=[0, 50, 100, 150, 200, 350],
    labels=[
        "very_short",
        "short",
        "medium",
        "long",
        "very_long"
    ]
)

# Conversation-length groups

candidates["conversation_length_group"] = pd.cut(
    candidates["conversation_length"],
    bins=[0, 2, 4, 7, 15, float("inf")],
    labels=[
        "short",
        "medium",
        "long",
        "very_long",
        "extreme"
    ]
)

print(
    candidates[
        [
            "conversation_length_group",
            "message_length_group"
        ]
    ].value_counts()
)

conversation_length_group  message_length_group
short                      medium                  12848
medium                     medium                  11582
short                      short                    8482
long                       medium                   7331
medium                     short                    6043
very_long                  medium                   4490
short                      very_short               3662
                           long                     3564
medium                     long                     3327
long                       short                    3237
short                      very_long                2717
medium                     very_long                2598
long                       long                     2037
medium                     very_short               2030
long                       very_long                1731
very_long                  short                    1616
                           long                     1149
                           very_long                1056
extreme                    medium                    977
long                       very_short                830
very_long                  very_short                411
extreme                    short                     307
                           long                      275
                           very_long                 159
                           very_short                 50
Name: count, dtype: int64

In [ ]:
# Select a diverse 200-example evaluation set

golden_set = (
    candidates
    .groupby(
        [
            "conversation_length_group",
            "message_length_group"
        ],
        observed=True
    )
    .sample(
        frac=1,
        random_state=42
    )
)

# Take a balanced sample across the groups
golden_set = (
    golden_set
    .groupby(
        [
            "conversation_length_group",
            "message_length_group"
        ],
        observed=True
    )
    .head(10)
)

# If this gives more than 200, randomly reduce to exactly 200
golden_set = (
    golden_set
    .sample(
        n=min(200, len(golden_set)),
        random_state=42
    )
    .reset_index(drop=True)
)

print("Golden set size:", len(golden_set))

print(
    golden_set[
        [
            "conversation_id",
            "conversation_length",
            "message_length",
            "text"
        ]
    ].head(20)
)

Golden set size: 200
    conversation_id  conversation_length  message_length  \
0         2538181.0                    6             220
1         2876360.0                    2              33
2          169635.0                    3             222
3           71993.0                    4              65
4         1581323.0                    5              97
5         2119254.0                    8             183
6         2909062.0                   12             229
7           74438.0                    9             151
8         2681958.0                    2              35
9         1252190.0                    6              24
10         791549.0                   30              46
11         235707.0                   34              51
12        1501711.0                   25             164
13         485348.0                   16             266
14        2627604.0                    4              89
15         226168.0                   44             120
16        2767503.0                    9             300
17        2437761.0                    2              96
18        2843670.0                    9             129
19        2414426.0                    2             135

                                                                                                                                                                                                       text
0   @115850 @115821 It's been 11 days since I order a product from you people, I didn't even get a single response from the delivery team. What I can see in my page is delivery unsuccessful !!! It's n...
1                                                                                                                                                                         画集あまぞんくんで頼んでるんだけどええい！支払い番号はまだか…！！
2   Got sent this @115830 Black Friday deal earlier. It said there were 9 hours left so waited until I was home from work but the price has gone up to £211!!! Is this allowed?! #BlackFridayDeals @1183...
3                                                                                                                                         ぎゃあああ、Amazonまでクリック直前の画面縦ズレしやがった！　プライム体験とかいらんかったのに勝手に登録しやがったあああ！！！
4                                                                                                         Since I don’t have to sign for my packages can your carriers just leave them. @115821 @AmazonHelp
5                 So I realized I have 206 steam games, 40 gog games, and 13 Uplay games a couple of origin and twitch games...a large majority of them I got for free.\n\nI need to play my video games. 😅
6   @115833 My Alexa takes my request to play WETA (saying the letters) as a request for Wet Radio from Tune In. New behavior, started a couple months ago, worked fine before. Can't get to WETA at all...
7                                                   @115817 this is the package I received today.  This is just the beginning of the “delivery” season!  🤨 Gotta do better! @115821 https://t.co/u1UTtcoi1C
8                                                                                                                                                                       は？P3・P4・P4G・P5のサントラ全部無料かよ amazon神だな
9                                                                                                                                                                                  あー、Amazon……オフラインでも読めるんかな
10                                                                                                                                                           Mon colis est arrivé à bon port :D @AmazonHelp
11                                                                                                                                                      @115850 where is this ..... https://t.co/SIudl3fzbz
12                                     Wow Dept.: GMgr kept giving me 20 hours/week when I repeatedly asked for 40. 8 people have quit this week, no notice.Thanks God for 40hrs!🙏🏽 https://t.co/jmd8yw74TE
13  After years of buying, first time I ship with Amazon Logistic and it's just a quick way to throw away my money, 800 $ lost in merchandise and you just can not be held responsible. What good polici...
14                                                                                                                @116316 Hab mir Star Wars Bettlefront 2 vorbestellt und es ist immernoch nicht angekommen
15                                                                                 Watch amazon and Nokia #UniteFor #Fun by bringing the sensational new Nokia 6 to fans all across India. #AmazonExclusive
16  @AmazonHelp Bonjour, j'ai passé une énorme commande informatique et j'ai reçu mon 1er paquet : pour un item à 100€ ça vous semble normal de le recevoir dans cet état ? Je me suis faite livrée au t...
17                                                                                                         @AmazonHelp I love firetv, but I can't keep it if I can't run Hulu Live TV. PLEASE HELP!!!!!!!!!
18                                                                       Hi @115821 &amp; @1016 \nIs there a problem with your 1-click buying platform? Keeps crashing when I try by an audio book with you
19                                                                  I order &amp; paid, then requested an update card, and I update it then they tell me to pay again but I already pay be fore @AmazonHelp

In [ ]:
golden_set.to_csv(
    "amazonhelp_golden_set_raw.csv",
    index=False
)

print("Golden set saved.")

Golden set saved.

In [ ]:
print("Golden set size:", len(golden_set))
print(golden_set.head(20))

Golden set size: 200
    conversation_id  tweet_id author_id  inbound                created_at  \
0         2538181.0   2538181    721911     True 2017-11-16 09:13:06+00:00
1         2876360.0   2876360    798485     True 2017-11-28 05:40:56+00:00
2          169635.0    169635    155505     True 2017-11-24 21:01:33+00:00
3           71993.0     71993    132154     True 2017-11-29 20:02:48+00:00
4         1581323.0   1581323    306603     True 2017-11-04 18:48:06+00:00
5         2119254.0   2119254    624534     True 2017-11-08 14:43:00+00:00
6         2909062.0   2909062    805420     True 2017-11-28 21:04:02+00:00
7           74438.0     74438    132665     True 2017-11-29 02:43:14+00:00
8         2681958.0   2681958    754455     True 2017-11-25 23:33:19+00:00
9         1252190.0   1252190    413736     True 2017-10-26 04:54:46+00:00
10         791549.0    791549    216940     True 2017-10-12 12:32:09+00:00
11         235707.0    235707    172139     True 2017-10-04 03:48:39+00:00
12        1501711.0   1501711    468562     True 2017-05-25 12:56:51+00:00
13         485348.0    485348    230469     True 2017-12-01 15:02:22+00:00
14        2627604.0   2627604    742146     True 2017-11-17 16:41:06+00:00
15         226168.0    226168    115850     True 2017-09-21 17:15:43+00:00
16        2767503.0   2767503    773888     True 2017-11-21 11:07:59+00:00
17        2437761.0   2437761    699279     True 2017-10-29 15:37:28+00:00
18        2843670.0   2843670    319988     True 2017-11-27 17:32:04+00:00
19        2414426.0   2414426    446836     True 2017-11-14 17:25:30+00:00

                                                                                                                                                                                                       text  \
0   @115850 @115821 It's been 11 days since I order a product from you people, I didn't even get a single response from the delivery team. What I can see in my page is delivery unsuccessful !!! It's n...
1                                                                                                                                                                         画集あまぞんくんで頼んでるんだけどええい！支払い番号はまだか…！！
2   Got sent this @115830 Black Friday deal earlier. It said there were 9 hours left so waited until I was home from work but the price has gone up to £211!!! Is this allowed?! #BlackFridayDeals @1183...
3                                                                                                                                         ぎゃあああ、Amazonまでクリック直前の画面縦ズレしやがった！　プライム体験とかいらんかったのに勝手に登録しやがったあああ！！！
4                                                                                                         Since I don’t have to sign for my packages can your carriers just leave them. @115821 @AmazonHelp
5                 So I realized I have 206 steam games, 40 gog games, and 13 Uplay games a couple of origin and twitch games...a large majority of them I got for free.\n\nI need to play my video games. 😅
6   @115833 My Alexa takes my request to play WETA (saying the letters) as a request for Wet Radio from Tune In. New behavior, started a couple months ago, worked fine before. Can't get to WETA at all...
7                                                   @115817 this is the package I received today.  This is just the beginning of the “delivery” season!  🤨 Gotta do better! @115821 https://t.co/u1UTtcoi1C
8                                                                                                                                                                       は？P3・P4・P4G・P5のサントラ全部無料かよ amazon神だな
9                                                                                                                                                                                  あー、Amazon……オフラインでも読めるんかな
10                                                                                                                                                           Mon colis est arrivé à bon port :D @AmazonHelp
11                                                                                                                                                      @115850 where is this ..... https://t.co/SIudl3fzbz
12                                     Wow Dept.: GMgr kept giving me 20 hours/week when I repeatedly asked for 40. 8 people have quit this week, no notice.Thanks God for 40hrs!🙏🏽 https://t.co/jmd8yw74TE
13  After years of buying, first time I ship with Amazon Logistic and it's just a quick way to throw away my money, 800 $ lost in merchandise and you just can not be held responsible. What good polici...
14                                                                                                                @116316 Hab mir Star Wars Bettlefront 2 vorbestellt und es ist immernoch nicht angekommen
15                                                                                 Watch amazon and Nokia #UniteFor #Fun by bringing the sensational new Nokia 6 to fans all across India. #AmazonExclusive
16  @AmazonHelp Bonjour, j'ai passé une énorme commande informatique et j'ai reçu mon 1er paquet : pour un item à 100€ ça vous semble normal de le recevoir dans cet état ? Je me suis faite livrée au t...
17                                                                                                         @AmazonHelp I love firetv, but I can't keep it if I can't run Hulu Live TV. PLEASE HELP!!!!!!!!!
18                                                                       Hi @115821 &amp; @1016 \nIs there a problem with your 1-click buying platform? Keeps crashing when I try by an audio book with you
19                                                                  I order &amp; paid, then requested an update card, and I update it then they tell me to pay again but I already pay be fore @AmazonHelp

                                                                      response_tweet_id  \
0                                                                               2538178
1                                                                               2876359
2                                                                                169633
3                                                                                 71992
4                                                                               1581321
5                                                                               2119253
6                                                                               2909060
7                                                                     74439,74440,74437
8                                                                               2681957
9                                                                               1252188
10                                                                               791548
11                                                                               235706
12                                                                              1501710
13                                                                        485349,485347
14                                                                              2627603
15  226169,226167,226170,226171,226172,226173,226174,226175,226176,226177,226178,226179
16                                                                      2767501,2767504
17                                                                              2437760
18                                                                              2843668
19                                                                              2414425

    in_response_to_tweet_id  message_length  conversation_length  \
0                 2538178.0             220                    6
1                       NaN              33                    2
2                  169633.0             222                    3
3                   71992.0              65                    4
4                 1581323.0              97                    5
5                 2119254.0             183                    8
6                 2909060.0             229                   12
7                   74440.0             151                    9
8                       NaN              35                    2
9                 1252188.0              24                    6
10                 791548.0              46                   30
11                 235706.0              51                   34
12                1501711.0             164                   25
13                 485347.0             266                   16
14                2627603.0              89                    4
15                 226168.0             120                   44
16                2767501.0             300                    9
17                      NaN              96                    2
18                2843668.0             129                    9
19                      NaN             135                    2

   message_length_group conversation_length_group
0             very_long                      long
1            very_short                     short
2             very_long                    medium
3                 short                    medium
4                 short                      long
5                  long                 very_long
6             very_long                 very_long
7                  long                 very_long
8            very_short                     short
9            very_short                      long
10           very_short                   extreme
11                short                   extreme
12                 long                   extreme
13            very_long                   extreme
14                short                    medium
15               medium                   extreme
16            very_long                 very_long
17                short                     short
18               medium                 very_long
19               medium                     short

In [ ]:
# Freeze the 200 selected conversation IDs

golden_ids = set(golden_set["conversation_id"])

# Get every tweet/message belonging to these conversations
golden_conversations = all_tweets[
    all_tweets["conversation_id"].isin(golden_ids)
].copy()

# Sort messages chronologically
golden_conversations = golden_conversations.sort_values(
    ["conversation_id", "created_at"]
)

print("Golden conversations:", golden_conversations["conversation_id"].nunique())
print("Total messages:", len(golden_conversations))

print("\nMessages per conversation:")
print(
    golden_conversations
    .groupby("conversation_id")
    .size()
    .describe()
)

KeyError: 'created_at'

In [ ]:
print(golden_conversations.columns.tolist())

['tweet_id', 'in_response_to_tweet_id', 'conversation_id']

In [ ]:
print(golden_conversations.head())

       tweet_id  in_response_to_tweet_id  conversation_id
18851     24561                  24562.0          24562.0
18852     24562                      NaN          24562.0
18853     24563                  24562.0          24562.0
20107     25950                  24564.0          24562.0
20108     24564                  24562.0          24562.0

In [ ]:
print(all_tweets.columns.tolist())

['tweet_id', 'in_response_to_tweet_id', 'conversation_id']

In [ ]:
# Convert Golden Set conversation IDs to integers
golden_ids = (
    golden_set["conversation_id"]
    .dropna()
    .astype(int)
    .unique()
)

print("Golden conversation IDs:", len(golden_ids))

Golden conversation IDs: 200

In [ ]:
placeholders = ",".join(["?"] * len(golden_ids))

query = f"""
SELECT
    tweet_id,
    author_id,
    inbound,
    created_at,
    text,
    response_tweet_id,
    in_response_to_tweet_id,
    conversation_id
FROM tweets
WHERE conversation_id IN ({placeholders})
"""

golden_conversations = pd.read_sql_query(
    query,
    conn,
    params=golden_ids.tolist()
)

print("Golden messages loaded:", len(golden_conversations))
print(
    "Golden conversations:",
    golden_conversations["conversation_id"].nunique()
)

DatabaseError: Execution failed on sql '
SELECT
    tweet_id,
    author_id,
    inbound,
    created_at,
    text,
    response_tweet_id,
    in_response_to_tweet_id,
    conversation_id
FROM tweets
WHERE conversation_id IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
': no such column: text

In [ ]:
# Check the actual columns in the tweets table
schema = pd.read_sql_query(
    "PRAGMA table_info(tweets)",
    conn
)

print(schema)

   cid                     name     type  notnull dflt_value  pk
0    0                 tweet_id  INTEGER        0       None   0
1    1                author_id     TEXT        0       None   0
2    2                  inbound  INTEGER        0       None   0
3    3               created_at     TEXT        0       None   0
4    4  in_response_to_tweet_id     REAL        0       None   0

In [ ]:
print(schema["name"].tolist())

['tweet_id', 'author_id', 'inbound', 'created_at', 'in_response_to_tweet_id']

In [ ]:
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn
)

print(tables)

     name
0  tweets

In [ ]:
for table in tables["name"]:
    print("\nTABLE:", table)

    cols = pd.read_sql_query(
        f"PRAGMA table_info('{table}')",
        conn
    )

    print(cols["name"].tolist())

TABLE: tweets
['tweet_id', 'author_id', 'inbound', 'created_at', 'in_response_to_tweet_id']

In [ ]:
import os
import glob

print("Current folder:")
print(os.getcwd())

print("\nCSV files:")
for f in glob.glob("**/*.csv", recursive=True):
    print(f)

Current folder:
d:\Internship tasks\hiver-support-agent\notebooks

CSV files:
amazonhelp_golden_set_raw.csv

In [ ]:
print("\nParquet files:")
for f in glob.glob("**/*.parquet", recursive=True):
    print(f)

Parquet files:

In [ ]:
import pandas as pd

golden_raw = pd.read_csv("amazonhelp_golden_set_raw.csv")

print("Shape:", golden_raw.shape)
print("\nColumns:")
print(golden_raw.columns.tolist())

print("\nFirst 5 rows:")
print(golden_raw.head())

Shape: (200, 12)

Columns:
['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']

First 5 rows:
   conversation_id  tweet_id  author_id  inbound                 created_at  \
0        2538181.0   2538181     721911     True  2017-11-16 09:13:06+00:00
1        2876360.0   2876360     798485     True  2017-11-28 05:40:56+00:00
2         169635.0    169635     155505     True  2017-11-24 21:01:33+00:00
3          71993.0     71993     132154     True  2017-11-29 20:02:48+00:00
4        1581323.0   1581323     306603     True  2017-11-04 18:48:06+00:00

                                                                                                                                                                                                      text  \
0  @115850 @115821 It's been 11 days since I order a product from you people, I didn't even get a single response from the delivery team. What I can see in my page is delivery unsuccessful !!! It's n...
1                                                                                                                                                                        画集あまぞんくんで頼んでるんだけどええい！支払い番号はまだか…！！
2  Got sent this @115830 Black Friday deal earlier. It said there were 9 hours left so waited until I was home from work but the price has gone up to £211!!! Is this allowed?! #BlackFridayDeals @1183...
3                                                                                                                                        ぎゃあああ、Amazonまでクリック直前の画面縦ズレしやがった！　プライム体験とかいらんかったのに勝手に登録しやがったあああ！！！
4                                                                                                        Since I don’t have to sign for my packages can your carriers just leave them. @115821 @AmazonHelp

  response_tweet_id  in_response_to_tweet_id  message_length  \
0           2538178                2538178.0             220
1           2876359                      NaN              33
2            169633                 169633.0             222
3             71992                  71992.0              65
4           1581321                1581323.0              97

   conversation_length message_length_group conversation_length_group
0                    6            very_long                      long
1                    2           very_short                     short
2                    3            very_long                    medium
3                    4                short                    medium
4                    5                short                      long

In [ ]:
print("\nData types:")
print(golden_raw.dtypes)

Data types:
conversation_id              float64
tweet_id                       int64
author_id                      int64
inbound                         bool
created_at                       str
text                             str
response_tweet_id                str
in_response_to_tweet_id      float64
message_length                 int64
conversation_length            int64
message_length_group             str
conversation_length_group        str
dtype: object

In [ ]:
print("\nMissing values:")
print(golden_raw.isnull().sum())

Missing values:
conversation_id               0
tweet_id                      0
author_id                     0
inbound                       0
created_at                    0
text                          0
response_tweet_id             0
in_response_to_tweet_id      47
message_length                0
conversation_length           0
message_length_group          0
conversation_length_group     0
dtype: int64

In [ ]:
print("Golden Set shape:", golden_raw.shape)

print("Unique conversations:",
      golden_raw["conversation_id"].nunique())

print("Unique tweets:",
      golden_raw["tweet_id"].nunique())

print("\nConversation length:")
print(
    golden_raw
    .groupby("conversation_id")
    .size()
    .describe()
)

Golden Set shape: (200, 12)
Unique conversations: 200
Unique tweets: 200

Conversation length:
count    200.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
dtype: float64

In [ ]:
golden_conversations = golden_raw.copy()

# Convert conversation_id to integer
golden_conversations["conversation_id"] = (
    golden_conversations["conversation_id"]
    .astype(int)
)

# Convert created_at to datetime
golden_conversations["created_at"] = pd.to_datetime(
    golden_conversations["created_at"],
    errors="coerce"
)

# Sort chronologically
golden_conversations = golden_conversations.sort_values(
    ["conversation_id", "created_at"]
).reset_index(drop=True)

print("Clean Golden Set created.")
print("Conversations:",
      golden_conversations["conversation_id"].nunique())
print("Messages:",
      len(golden_conversations))

Clean Golden Set created.
Conversations: 200
Messages: 200

In [ ]:
conversation_lengths = (
    golden_conversations
    .groupby("conversation_id")
    .size()
    .sort_values(ascending=False)
)

print(conversation_lengths.head(20))

conversation_id
24562     1
33205     1
71993     1
74438     1
83499     1
91296     1
101802    1
105211    1
123442    1
127468    1
134804    1
138973    1
153658    1
158606    1
169635    1
179299    1
226163    1
226168    1
231351    1
235707    1
dtype: int64

In [ ]:
print("\nLength distribution:")
print(conversation_lengths.value_counts().sort_index())

Length distribution:
1    200
Name: count, dtype: int64

In [ ]:
def format_conversation(conversation_id):
    conversation = golden_conversations[
        golden_conversations["conversation_id"] == conversation_id
    ].sort_values("created_at")

    messages = []

    for _, row in conversation.iterrows():

        speaker = (
            "CUSTOMER"
            if row["inbound"]
            else "AMAZONHELP"
        )

        messages.append(
            f"[{speaker}]\n{row['text']}"
        )

    return "\n\n".join(messages)

In [ ]:
print(format_conversation(91296))

[CUSTOMER]
@AmazonHelp Package due to be delivered today. Two hours ago your tracking page said "Driver is making 3 deliveries before yours", now it says there are "7 deliveries before yours". Is it being delivered in a DeLorean per chance? #backtothefuture #timemachine

In [ ]:
print(golden_conversations.shape)

print(golden_conversations["conversation_id"].head(10).tolist())

print(271913 in golden_conversations["conversation_id"].values)

(200, 12)
[24562, 33205, 71993, 74438, 83499, 91296, 101802, 105211, 123442, 127468]
False

In [ ]:
test = golden_conversations[
    golden_conversations["conversation_id"] == 91296
]

print("Rows found:", len(test))
print(test)

Rows found: 1
   conversation_id  tweet_id  author_id  inbound                created_at  \
5            91296     91296     135799     True 2017-11-30 15:04:59+00:00

                                                                                                                                                                                                      text  \
5  @AmazonHelp Package due to be delivered today. Two hours ago your tracking page said "Driver is making 3 deliveries before yours", now it says there are "7 deliveries before yours". Is it being de...

  response_tweet_id  in_response_to_tweet_id  message_length  \
5             91294                  91294.0             259

   conversation_length message_length_group conversation_length_group
5                    5            very_long                      long

In [ ]:
target_id = 271913

test = golden_conversations[
    golden_conversations["conversation_id"] == target_id
].copy()

print("Target conversation:", target_id)
print("Rows found:", len(test))

if len(test) > 0:
    print("\nActual conversation IDs found:")
    print(test["conversation_id"].tolist())

    print("\nMessages:")
    print(test["text"].tolist())
else:
    print("Conversation not found.")

Target conversation: 271913
Rows found: 0
Conversation not found.

In [ ]:
print(golden_conversations["conversation_id"].dtype)

print(
    golden_conversations[
        golden_conversations["conversation_id"].astype("Int64") == 271913
    ][["conversation_id", "tweet_id", "text"]]
)

int64
Empty DataFrame
Columns: [conversation_id, tweet_id, text]
Index: []

In [ ]:
golden_ids = golden_conversations["conversation_id"].dropna().unique()

print("Number of golden conversations:", len(golden_ids))

print("\nFirst 10 golden conversation IDs:")
print(golden_ids[:10])

Number of golden conversations: 200

First 10 golden conversation IDs:
[ 24562  33205  71993  74438  83499  91296 101802 105211 123442 127468]

In [ ]:
target_id = golden_ids[0]

print("Testing conversation:", target_id)

test = golden_conversations[
    golden_conversations["conversation_id"] == target_id
].sort_values("created_at")

print("\nMessages found:", len(test))
print("\nColumns:")
print(test.columns.tolist())

print("\nMessages:")
print(test["text"].tolist())

Testing conversation: 24562

Messages found: 1

Columns:
['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']

Messages:
["@115850 @121294 Yesterday my LGQ6 was delivered and I complain for its heating issue but didn't get any appropriate response."]

In [ ]:
print(format_conversation(target_id))

[CUSTOMER]
@115850 @121294 Yesterday my LGQ6 was delivered and I complain for its heating issue but didn't get any appropriate response.

In [ ]:
golden_ids = golden_conversations["conversation_id"].dropna().unique()

print("Number of golden conversations:", len(golden_ids))
print("\nFirst 10 golden conversation IDs:")
print(golden_ids[:10])

Number of golden conversations: 200

First 10 golden conversation IDs:
[ 24562  33205  71993  74438  83499  91296 101802 105211 123442 127468]

In [ ]:
target_id = golden_ids[0]

print("Testing conversation:", target_id)

test = golden_conversations[
    golden_conversations["conversation_id"] == target_id
].sort_values("created_at")

print("\nMessages found:", len(test))
print("\nMessages:")
print(test["text"].tolist())

Testing conversation: 24562

Messages found: 1

Messages:
["@115850 @121294 Yesterday my LGQ6 was delivered and I complain for its heating issue but didn't get any appropriate response."]

In [ ]:
# Count messages belonging to each conversation
conversation_counts = (
    all_tweets
    .groupby("conversation_id")
    .size()
    .sort_values(ascending=False)
)

print("Total conversations:", len(conversation_counts))

print("\nConversation length distribution:")
print(conversation_counts.describe())

print("\nTop 10 longest conversations:")
print(conversation_counts.head(10))

Total conversations: 798012

Conversation length distribution:
count    798012.000000
mean          3.523473
std           5.158453
min           2.000000
25%           2.000000
50%           2.000000
75%           4.000000
max        1390.000000
dtype: float64

Top 10 longest conversations:
conversation_id
625855.0     1390
776752.0     1060
37012.0       974
5965.0        802
88944.0       661
56184.0       651
2983023.0     650
615427.0      584
278169.0      551
2390546.0     534
dtype: int64

In [ ]:
# Find conversations with at least 3 messages
multi_message_ids = conversation_counts[
    conversation_counts >= 3
].index

print("Conversations with 3+ messages:", len(multi_message_ids))

# Pick one for testing
test_id = multi_message_ids[0]

print("Testing conversation:", test_id)
print("Message count:", conversation_counts.loc[test_id])

Conversations with 3+ messages: 362742
Testing conversation: 625855.0
Message count: 1390

In [ ]:
print("all_tweets columns:")
print(all_tweets.columns.tolist())

print("\ngolden_raw columns:")
print(golden_raw.columns.tolist())

all_tweets columns:
['tweet_id', 'in_response_to_tweet_id', 'conversation_id']

golden_raw columns:
['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']

In [ ]:
import pandas as pd

print("DataFrames currently available:\n")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(
            f"{name:25} "
            f"rows={len(obj):>10,} "
            f"columns={obj.columns.tolist()}"
        )

DataFrames currently available:

__                        rows=         4 columns=['brand', 'brand_tweets', 'conversations', 'avg_brand_replies', 'median_brand_replies']
___                       rows=         3 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
df_sample                 rows=     1,000 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
_4                        rows=        10 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
_6                        rows=        20 columns=['tweet_id', 'author_id', 'inbound', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
chunk                     rows=    11,774 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
brand_tweets              rows=   376,235 columns=['tweet_id', 'author_id', 'conversation_id']
customer_rows             rows=     6,749 columns=['author_id', 'inbound']
brand_rows                rows=     1,817 columns=['author_id', 'inbound']
brand_rows_for_brand      rows=       191 columns=['author_id', 'inbound']
amazon_ids                rows=   169,840 columns=['tweet_id', 'conversation_id']
selected                  rows=       893 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
amazon_df                 rows=   270,344 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
amazon_examples           rows=        20 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
matches                   rows=         0 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
_13                       rows=        20 columns=['tweet_id', 'author_id', 'inbound', 'text', 'in_response_to_tweet_id', 'response_tweet_id']
conversation              rows=         4 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
_14                       rows=         3 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
parent_df                 rows= 2,811,774 columns=['tweet_id', 'in_response_to_tweet_id']
customer_reply_ids        rows=   750,497 columns=['tweet_id', 'in_response_to_tweet_id']
all_tweets                rows= 2,811,774 columns=['tweet_id', 'in_response_to_tweet_id', 'conversation_id']
amazon_conversations      rows=   374,042 columns=['tweet_id', 'in_response_to_tweet_id', 'conversation_id']
brand_df                  rows=    43,265 columns=['tweet_id', 'author_id', 'conversation_id']
comparison_df             rows=         4 columns=['brand', 'brand_tweets', 'conversations', 'avg_brand_replies', 'median_brand_replies']
_43                       rows=         4 columns=['brand', 'brand_tweets', 'conversations', 'avg_brand_replies', 'median_brand_replies']
amazon_tweet_map          rows=   374,042 columns=['tweet_id', 'conversation_id']
part                      rows=     1,434 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
amazon_clean              rows=   374,042 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
_49                       rows=         5 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text']
intent_sample             rows=     4,874 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
customer_messages         rows=   203,598 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
intent_examples           rows=       200 columns=['conversation_id', 'text']
keyword_df                rows=        23 columns=['keyword', 'count']
_62                       rows=        23 columns=['keyword', 'count']
delivery_examples         rows=        43 columns=['conversation_id', 'text']
refund_examples           rows=        15 columns=['conversation_id', 'text']
prime_examples            rows=        14 columns=['conversation_id', 'text']
intent_keyword_df         rows=         9 columns=['intent', 'keyword_matches']
_69                       rows=         9 columns=['intent', 'keyword_matches']
first_customer_messages   rows=    82,534 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length']
candidates                rows=    82,509 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
golden_set                rows=       200 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
golden_conversations      rows=       200 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
schema                    rows=         5 columns=['cid', 'name', 'type', 'notnull', 'dflt_value', 'pk']
tables                    rows=         1 columns=['name']
cols                      rows=         5 columns=['cid', 'name', 'type', 'notnull', 'dflt_value', 'pk']
golden_raw                rows=       200 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
test                      rows=         1 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']

In [ ]:
print("=" * 70)
print("DATASET RELATIONSHIP AUDIT")
print("=" * 70)

# 1. all_tweets
print("\n1. all_tweets")
print("Rows:", len(all_tweets))
print("Columns:", all_tweets.columns.tolist())
print(all_tweets.head(3))

# 2. amazon_conversations
print("\n2. amazon_conversations")
print("Rows:", len(amazon_conversations))
print("Columns:", amazon_conversations.columns.tolist())
print(amazon_conversations.head(3))

# 3. golden_raw
print("\n3. golden_raw")
print("Rows:", len(golden_raw))
print("Columns:", golden_raw.columns.tolist())
print(golden_raw.head(3))

# 4. Check conversation IDs
print("\n" + "=" * 70)
print("CONVERSATION ID COUNTS")
print("=" * 70)

print(
    "all_tweets unique conversations:",
    all_tweets["conversation_id"].nunique()
)

print(
    "amazon_conversations unique conversations:",
    amazon_conversations["conversation_id"].nunique()
)

print(
    "golden_raw unique conversations:",
    golden_raw["conversation_id"].nunique()
)

# 5. Check tweet IDs
print("\n" + "=" * 70)
print("TWEET ID COUNTS")
print("=" * 70)

print(
    "all_tweets unique tweets:",
    all_tweets["tweet_id"].nunique()
)

print(
    "golden_raw unique tweets:",
    golden_raw["tweet_id"].nunique()
)

======================================================================
DATASET RELATIONSHIP AUDIT
======================================================================

1. all_tweets
Rows: 2811774
Columns: ['tweet_id', 'in_response_to_tweet_id', 'conversation_id']
   tweet_id  in_response_to_tweet_id  conversation_id
0         1                      3.0              8.0
1         2                      1.0              8.0
2         3                      4.0              8.0

2. amazon_conversations
Rows: 374042
Columns: ['tweet_id', 'in_response_to_tweet_id', 'conversation_id']
     tweet_id  in_response_to_tweet_id  conversation_id
181       269                    272.0            272.0
182       270                    269.0            272.0
183       271                    269.0            272.0

3. golden_raw
Rows: 200
Columns: ['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
   conversation_id  tweet_id  author_id  inbound                 created_at  \
0        2538181.0   2538181     721911     True  2017-11-16 09:13:06+00:00
1        2876360.0   2876360     798485     True  2017-11-28 05:40:56+00:00
2         169635.0    169635     155505     True  2017-11-24 21:01:33+00:00

                                                                                                                                                                                                      text  \
0  @115850 @115821 It's been 11 days since I order a product from you people, I didn't even get a single response from the delivery team. What I can see in my page is delivery unsuccessful !!! It's n...
1                                                                                                                                                                        画集あまぞんくんで頼んでるんだけどええい！支払い番号はまだか…！！
2  Got sent this @115830 Black Friday deal earlier. It said there were 9 hours left so waited until I was home from work but the price has gone up to £211!!! Is this allowed?! #BlackFridayDeals @1183...

  response_tweet_id  in_response_to_tweet_id  message_length  \
0           2538178                2538178.0             220
1           2876359                      NaN              33
2            169633                 169633.0             222

   conversation_length message_length_group conversation_length_group
0                    6            very_long                      long
1                    2           very_short                     short
2                    3            very_long                    medium

======================================================================
CONVERSATION ID COUNTS
======================================================================
all_tweets unique conversations: 798012
amazon_conversations unique conversations: 82534
golden_raw unique conversations: 200

======================================================================
TWEET ID COUNTS
======================================================================
all_tweets unique tweets: 2811774
golden_raw unique tweets: 200

In [ ]:
print("=" * 70)
print("DATASET CONNECTION CHECK")
print("=" * 70)

# --------------------------------------------------
# 1. Golden conversation IDs
# --------------------------------------------------

golden_conv_ids = set(
    golden_raw["conversation_id"]
    .dropna()
    .astype("int64")
)

print("\nGolden conversations:", len(golden_conv_ids))


# --------------------------------------------------
# 2. Check against all_tweets
# --------------------------------------------------

all_tweet_conv_ids = set(
    all_tweets["conversation_id"]
    .dropna()
    .astype("int64")
)

golden_in_all = golden_conv_ids.intersection(
    all_tweet_conv_ids
)

print(
    "Golden conversations found in all_tweets:",
    len(golden_in_all)
)

print(
    "Golden conversations NOT found in all_tweets:",
    len(golden_conv_ids - all_tweet_conv_ids)
)


# --------------------------------------------------
# 3. Check against amazon_conversations
# --------------------------------------------------

amazon_conv_ids = set(
    amazon_conversations["conversation_id"]
    .dropna()
    .astype("int64")
)

golden_in_amazon = golden_conv_ids.intersection(
    amazon_conv_ids
)

print(
    "Golden conversations found in amazon_conversations:",
    len(golden_in_amazon)
)

print(
    "Golden conversations NOT found in amazon_conversations:",
    len(golden_conv_ids - amazon_conv_ids)
)


# --------------------------------------------------
# 4. Compare tweet IDs
# --------------------------------------------------

golden_tweet_ids = set(
    golden_raw["tweet_id"]
    .dropna()
    .astype("int64")
)

all_tweet_ids = set(
    all_tweets["tweet_id"]
    .dropna()
    .astype("int64")
)

golden_tweets_in_all = golden_tweet_ids.intersection(
    all_tweet_ids
)

print("\nGolden tweets:", len(golden_tweet_ids))

print(
    "Golden tweets found in all_tweets:",
    len(golden_tweets_in_all)
)

print(
    "Golden tweets NOT found in all_tweets:",
    len(golden_tweet_ids - all_tweet_ids)
)

======================================================================
DATASET CONNECTION CHECK
======================================================================

Golden conversations: 200
Golden conversations found in all_tweets: 200
Golden conversations NOT found in all_tweets: 0
Golden conversations found in amazon_conversations: 200
Golden conversations NOT found in amazon_conversations: 0

Golden tweets: 200
Golden tweets found in all_tweets: 200
Golden tweets NOT found in all_tweets: 0

In [ ]:
# ============================================================
# STEP 5.1 — CONVERSATION STATISTICS
# ============================================================

print("=" * 70)
print("CONVERSATION STATISTICS")
print("=" * 70)

# Number of messages in each conversation
conversation_stats = (
    amazon_conversations
    .groupby("conversation_id")
    .size()
    .reset_index(name="message_count")
)

print("\nTotal conversations:")
print(len(conversation_stats))

print("\nMessage count statistics:")
print(conversation_stats["message_count"].describe())

print("\nMessage count distribution:")
print(
    conversation_stats["message_count"]
    .value_counts()
    .sort_index()
    .head(20)
)

print("\nLongest conversations:")
print(
    conversation_stats
    .sort_values("message_count", ascending=False)
    .head(10)
)

======================================================================
CONVERSATION STATISTICS
======================================================================

Total conversations:
82534

Message count statistics:
count    82534.000000
mean         4.531975
std          5.322001
min          2.000000
25%          2.000000
50%          3.000000
75%          5.000000
max        448.000000
Name: message_count, dtype: float64

Message count distribution:
message_count
2     31290
3     11572
4     14014
5      6060
6      5947
7      3159
8      2797
9      1701
10     1385
11      952
12      713
13      500
14      391
15      285
16      289
17      208
18      180
19      145
20      113
21       96
Name: count, dtype: int64

Longest conversations:
       conversation_id  message_count
13090         395394.0            448
78              5159.0            448
13159         397889.0            425
346            19137.0            218
30122         964970.0            207
36808        1208753.0            161
21957         665469.0            141
8237          279455.0            139
27707         865815.0            128
192            12549.0            124

In [ ]:
# ============================================================
# STEP 5.2 — RECONSTRUCT ONE CONVERSATION
# ============================================================

# Pick a conversation that has multiple messages
example_conversation_id = (
    conversation_stats
    .sort_values("message_count", ascending=False)
    .iloc[0]["conversation_id"]
)

print("Example conversation ID:", example_conversation_id)

# Get all tweets belonging to this conversation
example = (
    golden_raw[
        golden_raw["conversation_id"] == example_conversation_id
    ]
    .sort_values("created_at")
)

print("\nMessages found:", len(example))

print("\n" + "=" * 70)
print("CONVERSATION")
print("=" * 70)

for _, row in example.iterrows():

    speaker = (
        "CUSTOMER"
        if row["inbound"]
        else "AMAZONHELP"
    )

    print(f"\n[{speaker}]")
    print(row["text"])

Example conversation ID: 395394.0

Messages found: 0

======================================================================
CONVERSATION
======================================================================

In [ ]:
# ============================================================
# STEP 5.3 — FIND DATAFRAME CONTAINING TWEET TEXT
# ============================================================

print("=" * 70)
print("DATAFRAMES CONTAINING TEXT")
print("=" * 70)

for name, obj in list(globals().items()):

    if isinstance(obj, pd.DataFrame):

        if "text" in obj.columns:

            print(
                f"{name:30} "
                f"rows={len(obj):>10,} "
                f"columns={obj.columns.tolist()}"
            )

======================================================================
DATAFRAMES CONTAINING TEXT
======================================================================
___                            rows=         3 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
df_sample                      rows=     1,000 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
_4                             rows=        10 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
_6                             rows=        20 columns=['tweet_id', 'author_id', 'inbound', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
chunk                          rows=    11,774 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
selected                       rows=       893 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
amazon_df                      rows=   270,344 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
amazon_examples                rows=        20 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
matches                        rows=         0 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
_13                            rows=        20 columns=['tweet_id', 'author_id', 'inbound', 'text', 'in_response_to_tweet_id', 'response_tweet_id']
conversation                   rows=         4 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
_14                            rows=         3 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
part                           rows=     1,434 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
amazon_clean                   rows=   374,042 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
_49                            rows=         5 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text']
intent_sample                  rows=     4,874 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
customer_messages              rows=   203,598 columns=['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
intent_examples                rows=       200 columns=['conversation_id', 'text']
delivery_examples              rows=        43 columns=['conversation_id', 'text']
refund_examples                rows=        15 columns=['conversation_id', 'text']
prime_examples                 rows=        14 columns=['conversation_id', 'text']
first_customer_messages        rows=    82,534 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length']
candidates                     rows=    82,509 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
golden_set                     rows=       200 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
golden_conversations           rows=       200 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
golden_raw                     rows=       200 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
test                           rows=         1 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']
example                        rows=         0 columns=['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length', 'message_length_group', 'conversation_length_group']

In [ ]:
# ============================================================
# STEP 5.1 — INSPECT AMAZON CLEAN
# ============================================================

print("=" * 70)
print("AMAZON CLEAN DATASET")
print("=" * 70)

print("\nRows:", len(amazon_clean))

print("\nColumns:")
print(amazon_clean.columns.tolist())

print("\nData types:")
print(amazon_clean.dtypes)

print("\nMissing values:")
print(amazon_clean.isnull().sum())

print("\nSample:")
print(
    amazon_clean.head(5).to_string(index=False)
)

======================================================================
AMAZON CLEAN DATASET
======================================================================

Rows: 374042

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']

Data types:
tweet_id                                 int64
author_id                                  str
inbound                                   bool
created_at                 datetime64[us, UTC]
text                                       str
response_tweet_id                          str
in_response_to_tweet_id                float64
conversation_id                        float64
dtype: object

Missing values:
tweet_id                        0
author_id                       0
inbound                         0
created_at                      0
text                            0
response_tweet_id          120090
in_response_to_tweet_id     81902
conversation_id                 0
dtype: int64

Sample:
 tweet_id  author_id  inbound                created_at                                                                                                                           text response_tweet_id  in_response_to_tweet_id  conversation_id
      272     115770     True 2017-11-22 09:14:39+00:00                                                                                                       amazonのfireTVstickが見れない😢               269                      NaN            272.0
      269 AmazonHelp    False 2017-11-22 09:23:01+00:00 @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET           270,271                    272.0            272.0
      270     115770     True 2017-11-22 09:24:30+00:00                                                                                  @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。               NaN                    269.0            272.0
      271     115770     True 2017-11-22 09:30:36+00:00                                                               @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。               273                    269.0            272.0
      273 AmazonHelp    False 2017-11-22 09:40:27+00:00                                                          @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET               274                    271.0            272.0

In [ ]:
# ============================================================
# STEP 5.2 — CONVERSATION QUALITY CHECK
# ============================================================

print("=" * 70)
print("CONVERSATION QUALITY")
print("=" * 70)

# Number of messages in each conversation
amazon_conv_stats = (
    amazon_clean
    .groupby("conversation_id")
    .size()
    .reset_index(name="message_count")
)

print("\nTotal conversations:")
print(len(amazon_conv_stats))

print("\nMessages per conversation:")
print(
    amazon_conv_stats["message_count"].describe()
)

print("\nConversations by message count:")
print(
    amazon_conv_stats["message_count"]
    .value_counts()
    .sort_index()
    .head(15)
)

======================================================================
CONVERSATION QUALITY
======================================================================

Total conversations:
82534

Messages per conversation:
count    82534.000000
mean         4.531975
std          5.322001
min          2.000000
25%          2.000000
50%          3.000000
75%          5.000000
max        448.000000
Name: message_count, dtype: float64

Conversations by message count:
message_count
2     31290
3     11572
4     14014
5      6060
6      5947
7      3159
8      2797
9      1701
10     1385
11      952
12      713
13      500
14      391
15      285
16      289
Name: count, dtype: int64

In [ ]:
# ============================================================
# STEP 5.3 — SELECT A REAL CONVERSATION
# ============================================================

# Pick a conversation with at least 5 messages
candidate_conversations = (
    amazon_conv_stats[
        amazon_conv_stats["message_count"] >= 5
    ]
    .sort_values("message_count", ascending=False)
)

example_conversation_id = candidate_conversations.iloc[0]["conversation_id"]

print("Selected conversation:", example_conversation_id)

print(
    "Message count:",
    candidate_conversations.iloc[0]["message_count"]
)

Selected conversation: 5159.0
Message count: 448.0

In [ ]:
# ============================================================
# STEP 5.4 — DISPLAY COMPLETE CONVERSATION
# ============================================================

example_conversation = (
    amazon_clean[
        amazon_clean["conversation_id"] == example_conversation_id
    ]
    .sort_values("created_at")
)

print("=" * 70)
print("COMPLETE CONVERSATION")
print("=" * 70)

print(
    "Conversation ID:",
    example_conversation_id
)

print(
    "Messages:",
    len(example_conversation)
)

for _, row in example_conversation.iterrows():

    speaker = (
        "CUSTOMER"
        if row["inbound"]
        else "AMAZONHELP"
    )

    print("\n" + "-" * 50)
    print(f"[{speaker}]")
    print(row["text"])

======================================================================
COMPLETE CONVERSATION
======================================================================
Conversation ID: 5159.0
Messages: 448

--------------------------------------------------
[CUSTOMER]
Hit ❤ or re-tweet to get notified when the OnePlus 5T sale begins, exclusively on Amazon. Stay tuned to get #ANewView. https://t.co/0Ci7j8Lsoo

--------------------------------------------------
[CUSTOMER]
@115850 Im Waiting 😜

--------------------------------------------------
[CUSTOMER]
@140735 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 #amazonfestiveriddles@JeffBezos  @115850 @AmazonHelp
चोरो मुझे मेरे इन ऑडर के पैसे दो #AmazonGreatIndianFestivalSell बोलकर बेवकूफ बना रहे हो उपभोक्ताओं को
#Cashback मिलेगा बोलकर अब मुकर गए
कितनी ही बार तुमको ऑडर डिटेल भी सेंड कर दी है लिंक में देखो
https://t.co/o7HHLlYBJj

--------------------------------------------------
[CUSTOMER]
@115850 Can i get one for free please i am a regular customer

--------------------------------------------------
[CUSTOMER]
@115850 Got any job for me so that I can earn ₹33K to spend on 5T?

--------------------------------------------------
[CUSTOMER]
@115850 Where I find Diwali winner results

--------------------------------------------------
[CUSTOMER]
@115850 Redmi 4a 32gb stock me aaye tab बताना.

--------------------------------------------------
[CUSTOMER]
@284702 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 How much does it cost ?

--------------------------------------------------
[AMAZONHELP]
@140735 I'm afraid we do not have such option. However, you may take the advantage of the offers and deals from our website. ^HS

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Ok

--------------------------------------------------
[AMAZONHELP]
@284286 Thanks for understanding. Wiish you the very best for the next sale.😉 ^RB

--------------------------------------------------
[AMAZONHELP]
@116925 I'm sorry for the inconvenience, please share your details here https://t.co/GIJyeYqKE0, we would look into this. Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ ^MD

--------------------------------------------------
[AMAZONHELP]
@284281 Well, if you're really interested, you might want to click here: https://t.co/NlW54e35cA :P Also, we're sure it's going to be worth the wait!^MD

--------------------------------------------------
[AMAZONHELP]
@284271 Could you please confirm which contest are you referring to so that we can assist you? ^GD

--------------------------------------------------
[AMAZONHELP]
@140735 Thanks for understanding, Jayant. ^KA

--------------------------------------------------
[AMAZONHELP]
@284268 Please click on notify by visiting this link: https://t.co/BCTx4FNxeC. You will be notified via email before the sale begins. Appreciate your interest. ^HS

--------------------------------------------------
[AMAZONHELP]
@284702 You may check the price here: https://t.co/h8Ob5KEh0y ^MN

--------------------------------------------------
[CUSTOMER]
@285585 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@285432 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Exchange available? One plus 5↔️ one plus 5T

--------------------------------------------------
[CUSTOMER]
@285444 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@285437 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Is there any exchange program as I already have OnePlus 5.

--------------------------------------------------
[CUSTOMER]
@115850 Thank you @115850 😍😍😍

--------------------------------------------------
[CUSTOMER]
@115850 When I Get My Refund Email id - __email__

--------------------------------------------------
[CUSTOMER]
@115850 Is it flash sale then can I get op5T?

--------------------------------------------------
[AMAZONHELP]
@285444 You're welcome. Do keep us posted for any further concerns. ^SG

--------------------------------------------------
[AMAZONHELP]
@285437 I'm sure you'd like to upgrade your device to the OnePlus 5T, Sasi. Considering it has just released and is available only on preview sale, exchange for this device isn't currently available. ^JC

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Thanks for letting me know.😍😍😘 Amazon

--------------------------------------------------
[AMAZONHELP]
@285432 I'd like to have a closer look at the refund issue. Please share your details in this link here: https://t.co/GIJyeYqKE0 and I'll reach out. Please don't provide your account details, we consider it to be personal information. Our page is visible to the public. ^KA

--------------------------------------------------
[AMAZONHELP]
@158565 Yes, it's a flash sale for OnePlus5T. You can purchase it from here: https://t.co/kkiatwZjOs during the sale. Good luck for the sale. ^VN

--------------------------------------------------
[CUSTOMER]
@115850 Customer service may problem hai. ..customers ko react nahi karte

--------------------------------------------------
[AMAZONHELP]
@285585 Considering that the mobile has launched recently and only available on flash sale, we do not have any annoucement regarding the availability of exchange for now. ^RI

--------------------------------------------------
[AMAZONHELP]
@285437 You're welcome. :) Do keep us posted for any further concerns. ^GD

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Thanks to reply.i definitely try to purchase op5T on Amazon India.In box any protection case is present.

--------------------------------------------------
[AMAZONHELP]
@285574 That's quite a remark. Could you please elaborate what went wrong so that we can assist you accordingly?

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Sure😍😍

--------------------------------------------------
[CUSTOMER]
@285794 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@AmazonHelp OKAY

--------------------------------------------------
[CUSTOMER]
@115850 Any exchange offer available?

--------------------------------------------------
[AMAZONHELP]
@158565 You're welcome. We've checked and looks like a case will not be included in the box. However, please stay tuned for the sale for more info on this. Appreciate your understanding. ^VN

--------------------------------------------------
[AMAZONHELP]
@285794 Considering that the phone has launched recently and only available on flash sale, we do not have any information on the availability of exchange offer. ^MN

--------------------------------------------------
[CUSTOMER]
@285775 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@286856 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Let's make a deal u show me... I gift den to two more...

--------------------------------------------------
[CUSTOMER]
@115850 What is the price , can you tell me ,so that i can manage my  credit first

--------------------------------------------------
[CUSTOMER]
@115850 Chor company

--------------------------------------------------
[CUSTOMER]
@145381 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Ur welcome

--------------------------------------------------
[CUSTOMER]
@AmazonHelp कितनी बार करना पड़ेगा डिटेल्स सेंड 7-8 बार तो कर ही चुका हूं पर तुम लोग भी पूरे कमीने हो

--------------------------------------------------
[AMAZONHELP]
@285775 We can apprehend to the connected excitement. Stay tuned on webpage for upcoming updates. ^CN

--------------------------------------------------
[AMAZONHELP]
@286856 Please check this link, here: https://t.co/KUQ6ZT1mPY for more information about the product and the promotions available at this moment. ^KA

--------------------------------------------------
[AMAZONHELP]
@145381 :) ^CB

--------------------------------------------------
[AMAZONHELP]
@286853 That's quite a remark. Could you please elaborate your concern so that we can assist you accordingly? ^GD

--------------------------------------------------
[CUSTOMER]
@219391 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Oneplus 5t = 32999, pixel 2 = 61000....cant understand where the 28000 went.....

--------------------------------------------------
[CUSTOMER]
@287434 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Thanks

--------------------------------------------------
[AMAZONHELP]
@219391 I'm sorry we're unable to apprehend you. Could you please elaborate on your concern so that we can assist you? ^GD

--------------------------------------------------
[CUSTOMER]
@115850 Sir is there oneplus 5t will be available regular sale after this preview sale :)

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Haha..im only trying to understand why the pixel 2 costs almost twice as the oneplus 5t, for the same features

--------------------------------------------------
[CUSTOMER]
@287910 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[AMAZONHELP]
@287434 We don't have any announcement on this yet; however, kindly stay tuned to the sale for more updates. Appreciate your understanding. ^VN

--------------------------------------------------
[CUSTOMER]
@288185 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 I want to know that there is any wholesale facilities of goods

--------------------------------------------------
[CUSTOMER]
@115850 Is there any Thanksgiving offer!?

--------------------------------------------------
[CUSTOMER]
@115850 I hope there will be a good exchange offer for Oneplus 5 users

--------------------------------------------------
[AMAZONHELP]
@287911 Considering that One plus 5T in on flash sale, we do not have any information regarding the availability of exchange option. ^KA

--------------------------------------------------
[AMAZONHELP]
@287910 Please connect with our support team here: https://t.co/vlvfJr4nN9 and we'll help you with your concern. ^HS

--------------------------------------------------
[AMAZONHELP]
@288185 We haven't made any announcement yet. Please stay tuned to the website for update on this. ^SG

--------------------------------------------------
[CUSTOMER]
@115850 when will available No cost Emi for the #oneplus5t from Bajaj .?

--------------------------------------------------
[CUSTOMER]
@288324 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Any offer on One plus 5t

--------------------------------------------------
[CUSTOMER]
@141820 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Youare cheatet you will sent me perfoum bottle inthe pacakge

--------------------------------------------------
[AMAZONHELP]
@286029 Considering that the mobile has been launched recently and is available only on flash sale, we have not made an announcement on the available payment options for now. ^RI

--------------------------------------------------
[CUSTOMER]
@AmazonHelp So not available for Todays sale ?.😔😔

--------------------------------------------------
[AMAZONHELP]
@141820 Apologies for the inconvenience. Have you reported this to our support team here: https://t.co/vlvfJr4nN9? We'll look into this for you. ^RB

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Do refund or not

--------------------------------------------------
[CUSTOMER]
@AmazonHelp You are teliing you will do refund know you are telling for investiagation 5998my product price given my money back cheater

--------------------------------------------------
[CUSTOMER]
@AmazonHelp I will contact cs please help me personaly

--------------------------------------------------
[CUSTOMER]
@AmazonHelp I nwed monet please give my miney back

--------------------------------------------------
[CUSTOMER]
@146167 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[AMAZONHELP]
@288324 Kindly refer the product page here: https://t.co/fsmQlKIP1n, to check for any available offers on One Plus 5T. ^MP

--------------------------------------------------
[CUSTOMER]
@115850 It would be even more good, if you offer NoCost emi on #OnePlus5T

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Thank you @115850

--------------------------------------------------
[AMAZONHELP]
@141820 I’m sorry about this experience,Ishika. Do not worry. Please share your details here: https://t.co/GIJyeYqKE0 and I'll get in touch with you. ^MK

--------------------------------------------------
[AMAZONHELP]
@146167 I get your concern about no cost EMI. You may check the availability during checkout process. Do keep us posted. ^SV

--------------------------------------------------
[AMAZONHELP]
@286029 I understand your concern about the no cost EMI option. I wish I could help you here, but as mentioned earlier, we do not have additional information on this for now. ^RI

--------------------------------------------------
[CUSTOMER]
@115850 CheTers

--------------------------------------------------
[AMAZONHELP]
@141820 I understand you're upset, Ishika. Request you to please fill in the details in the link mentioned earlier and we'll get this checked. ^MK

--------------------------------------------------
[CUSTOMER]
@AmazonHelp I was given detils thet investigate not issue

--------------------------------------------------
[CUSTOMER]
@AmazonHelp Refund

--------------------------------------------------
[AMAZONHELP]
@141820 Could you please confirm, submitting your details using the link shared here: https://t.co/D1NpwERFwx. ^MP

--------------------------------------------------
[CUSTOMER]
@143180 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Thanks for such a fastest delivery @115850 . Got my Flagship delivered right after the next day I ordered.

--------------------------------------------------
[AMAZONHELP]
@143180 Woohoo! That's awesome! Thank you indeed for keeping us inspired to do such great work. We appreciate the kind words and we're here to help if you need us :-) ^SV

--------------------------------------------------
[CUSTOMER]
@143579 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 I have not got my refunded money since I have replaced my order since 5 - 6 days please check

--------------------------------------------------
[AMAZONHELP]
@143579 Sorry for the inconvenience, Shreyash. Please report this to our support team here: https://t.co/TdDksLo6Mf and we'll look into this. ^MK

--------------------------------------------------
[CUSTOMER]
@115850 Are we going to have exchange offer today on @115850? Please keep, i wanna buy #OnePlus5t with exchange..

@AmazonHelp @132995 #OnePlus5TLaunch #OnePlusPopUp

--------------------------------------------------
[AMAZONHELP]
@143958 We don't have an announcement on this yet, Ketan. Request you to check the availability of exchange option while placing the order. ^MK

--------------------------------------------------
[CUSTOMER]
@144475 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Thanxx ☺

--------------------------------------------------
[CUSTOMER]
@144787 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[AMAZONHELP]
@144475 You are welcome, Sharon!

--------------------------------------------------
[CUSTOMER]
@144609 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Thanks👍

--------------------------------------------------
[CUSTOMER]
@115850 Okay for replied me

--------------------------------------------------
[AMAZONHELP]
@144609 You are most welcome and thank you for reaching out to us today. ^JS

--------------------------------------------------
[AMAZONHELP]
@144787 It was a pleasure assisting you. Do let us know if you need any further assistance. ^SY

--------------------------------------------------
[CUSTOMER]
@145103 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Sir any shoe?

--------------------------------------------------
[AMAZONHELP]
@145103 I'm sorry, I was unable to comprehend your concern. Could you please elaborate on your concern? ^SY

--------------------------------------------------
[CUSTOMER]
@145231 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@145223 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

--------------------------------------------------
[CUSTOMER]
@115850 Thank you @115850

--------------------------------------------------
[CUSTOMER]
@115850 I'm waiting for that ...

--------------------------------------------------
[CUSTOMER]
@144285 The #OnePlus5T preview sale on Amazon.in starts 12 PM. Are you ready to get #ANewView? https://t.co/ryB7j7wIZE

--------------------------------------------------
[CUSTOMER]
@147144 The #OnePlus5T preview sale on Amazon.in starts 12 PM. Are you ready to get #ANewView? https://t.co/ryB7j7wIZE

--------------------------------------------------
[AMAZONHELP]
@145231 You're welcome. Appreciate your understanding. ^EM

--------------------------------------------------
[CUSTOMER]
@151184 The #OnePlus5T preview sale on Amazon.in starts 12 PM. Are you ready to get #ANewView? https://t.co/ryB7j7wIZE

--------------------------------------------------
[CUSTOMER]
@115850 I am ready for the new view I bought one plus 5 it's one month old what will do for that so kindly exchange my old one plus 5 and I can buy new one plus 5T with better price.

--------------------------------------------------
[CUSTOMER]

In [ ]:
# ============================================================
# STEP 5.5 — BUILD CONVERSATION DOCUMENTS
# ============================================================

def build_conversation(row_group):
    """
    Convert all messages in one conversation
    into a single text document.
    """

    row_group = row_group.sort_values("created_at")

    messages = []

    for _, row in row_group.iterrows():

        speaker = (
            "CUSTOMER"
            if row["inbound"]
            else "AMAZONHELP"
        )

        text = str(row["text"]).strip()

        if text:
            messages.append(
                f"[{speaker}]: {text}"
            )

    return "\n".join(messages)


# Test on our example conversation
sample_document = build_conversation(example_conversation)

print("=" * 70)
print("SAMPLE CONVERSATION DOCUMENT")
print("=" * 70)

print(sample_document[:5000])

======================================================================
SAMPLE CONVERSATION DOCUMENT
======================================================================
[CUSTOMER]: Hit ❤ or re-tweet to get notified when the OnePlus 5T sale begins, exclusively on Amazon. Stay tuned to get #ANewView. https://t.co/0Ci7j8Lsoo
[CUSTOMER]: @115850 Im Waiting 😜
[CUSTOMER]: @140735 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 #amazonfestiveriddles@JeffBezos  @115850 @AmazonHelp
चोरो मुझे मेरे इन ऑडर के पैसे दो #AmazonGreatIndianFestivalSell बोलकर बेवकूफ बना रहे हो उपभोक्ताओं को
#Cashback मिलेगा बोलकर अब मुकर गए
कितनी ही बार तुमको ऑडर डिटेल भी सेंड कर दी है लिंक में देखो
https://t.co/o7HHLlYBJj
[CUSTOMER]: @115850 Can i get one for free please i am a regular customer
[CUSTOMER]: @115850 Got any job for me so that I can earn ₹33K to spend on 5T?
[CUSTOMER]: @115850 Where I find Diwali winner results
[CUSTOMER]: @115850 Redmi 4a 32gb stock me aaye tab बताना.
[CUSTOMER]: @284702 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 How much does it cost ?
[AMAZONHELP]: @140735 I'm afraid we do not have such option. However, you may take the advantage of the offers and deals from our website. ^HS
[CUSTOMER]: @AmazonHelp Ok
[AMAZONHELP]: @284286 Thanks for understanding. Wiish you the very best for the next sale.😉 ^RB
[AMAZONHELP]: @116925 I'm sorry for the inconvenience, please share your details here https://t.co/GIJyeYqKE0, we would look into this. Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ ^MD
[AMAZONHELP]: @284281 Well, if you're really interested, you might want to click here: https://t.co/NlW54e35cA :P Also, we're sure it's going to be worth the wait!^MD
[AMAZONHELP]: @284271 Could you please confirm which contest are you referring to so that we can assist you? ^GD
[AMAZONHELP]: @140735 Thanks for understanding, Jayant. ^KA
[AMAZONHELP]: @284268 Please click on notify by visiting this link: https://t.co/BCTx4FNxeC. You will be notified via email before the sale begins. Appreciate your interest. ^HS
[AMAZONHELP]: @284702 You may check the price here: https://t.co/h8Ob5KEh0y ^MN
[CUSTOMER]: @285585 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @285432 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 Exchange available? One plus 5↔️ one plus 5T
[CUSTOMER]: @285444 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @285437 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 Is there any exchange program as I already have OnePlus 5.
[CUSTOMER]: @115850 Thank you @115850 😍😍😍
[CUSTOMER]: @115850 When I Get My Refund Email id - __email__
[CUSTOMER]: @115850 Is it flash sale then can I get op5T?
[AMAZONHELP]: @285444 You're welcome. Do keep us posted for any further concerns. ^SG
[AMAZONHELP]: @285437 I'm sure you'd like to upgrade your device to the OnePlus 5T, Sasi. Considering it has just released and is available only on preview sale, exchange for this device isn't currently available. ^JC
[CUSTOMER]: @AmazonHelp Thanks for letting me know.😍😍😘 Amazon
[AMAZONHELP]: @285432 I'd like to have a closer look at the refund issue. Please share your details in this link here: https://t.co/GIJyeYqKE0 and I'll reach out. Please don't provide your account details, we consider it to be personal information. Our page is visible to the public. ^KA
[AMAZONHELP]: @158565 Yes, it's a flash sale for OnePlus5T. You can purchase it from here: https://t.co/kkiatwZjOs during the sale. Good luck for the sale. ^VN
[CUSTOMER]: @115850 Customer service may problem hai. ..customers ko react nahi karte
[AMAZONHELP]: @285585 Considering that the mobile has launched recently and only available on flash sale, we do not have any annoucement regarding the availability of exchange for now. ^RI
[AMAZONHELP]: @285437 You're welcome. :) Do keep us posted for any further concerns. ^GD
[CUSTOMER]: @AmazonHelp Thanks to reply.i definitely try to purchase op5T on Amazon India.In box any protection case is present.
[AMAZONHELP]: @285574 That's quite a remark. Could you please elaborate what went wrong so that we can assist you accordingly?
[CUSTOMER]: @AmazonHelp Sure😍😍
[CUSTOMER]: @285794 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @AmazonHelp OKAY
[CUSTOMER]: @115850 Any exchange offer available?
[AMAZONHELP]: @158565 You're welcome. We've checked and looks like a case will not be included in the box. However, please stay tuned for the sale for more info on this. Appreciate your understanding. ^VN
[AMAZONHELP]: @285794 Considering that the phone has launched recently and only available on flash sale, we do not have any information on the availability of exchange offer. ^MN
[CUSTOMER]: @285775 Thank you for your interest! You will be notified

In [ ]:
# ============================================================
# STEP 6.1 — FINAL DATASET CHECK
# ============================================================

print("=" * 70)
print("AMAZON CLEAN DATASET")
print("=" * 70)

print("Rows:", len(amazon_clean))
print("\nColumns:")
print(amazon_clean.columns.tolist())

print("\nMissing values:")
print(amazon_clean.isnull().sum())

print("\nUnique conversations:",
      amazon_clean["conversation_id"].nunique())

print("\nUnique tweets:",
      amazon_clean["tweet_id"].nunique())

print("\nInbound distribution:")
print(amazon_clean["inbound"].value_counts())

======================================================================
AMAZON CLEAN DATASET
======================================================================
Rows: 374042

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']

Missing values:
tweet_id                        0
author_id                       0
inbound                         0
created_at                      0
text                            0
response_tweet_id          120090
in_response_to_tweet_id     81902
conversation_id                 0
dtype: int64

Unique conversations: 82534

Unique tweets: 374042

Inbound distribution:
inbound
True     203598
False    170444
Name: count, dtype: int64

In [ ]:
# ============================================================
# STEP 6.2 — DATETIME NORMALIZATION
# ============================================================

amazon_clean["created_at"] = pd.to_datetime(
    amazon_clean["created_at"],
    utc=True,
    errors="coerce"
)

print("Invalid timestamps:",
      amazon_clean["created_at"].isna().sum())

print("\nDate range:")
print("Start:", amazon_clean["created_at"].min())
print("End:  ", amazon_clean["created_at"].max())

Invalid timestamps: 0

Date range:
Start: 2011-10-13 11:57:18+00:00
End:   2017-12-03 23:13:02+00:00

In [ ]:
# ============================================================
# STEP 6.3 — CONVERSATION-AWARE CHUNKING
# ============================================================

def create_conversation_chunks(
    df,
    max_messages=8,
    overlap=2
):
    """
    Create overlapping message windows inside each conversation.

    We keep conversation_id as metadata so retrieved chunks
    can later be grouped back together.
    """

    chunks = []

    # Sort everything chronologically
    df = df.sort_values(
        ["conversation_id", "created_at"]
    )

    for conversation_id, group in df.groupby(
        "conversation_id",
        sort=False
    ):

        group = group.reset_index(drop=True)

        # Create overlapping windows
        step = max_messages - overlap

        for start in range(
            0,
            len(group),
            step
        ):

            window = group.iloc[
                start:start + max_messages
            ]

            if len(window) == 0:
                continue

            messages = []

            for _, row in window.iterrows():

                speaker = (
                    "CUSTOMER"
                    if bool(row["inbound"])
                    else "AMAZONHELP"
                )

                text = str(row["text"]).strip()

                if not text:
                    continue

                messages.append(
                    f"[{speaker}]: {text}"
                )

            if not messages:
                continue

            chunks.append({
                "conversation_id": conversation_id,
                "start_message": start,
                "end_message": start + len(window) - 1,
                "text": "\n".join(messages),
                "message_count": len(messages)
            })

    return pd.DataFrame(chunks)

In [ ]:
conversation_chunks = create_conversation_chunks(
    amazon_clean,
    max_messages=8,
    overlap=2
)

print("=" * 70)
print("CONVERSATION CHUNKS")
print("=" * 70)

print("Total chunks:", len(conversation_chunks))

print("\nColumns:")
print(conversation_chunks.columns.tolist())

print("\nSample:")
print(conversation_chunks.head(3).to_string(index=False))

======================================================================
CONVERSATION CHUNKS
======================================================================
Total chunks: 102108

Columns:
['conversation_id', 'start_message', 'end_message', 'text', 'message_count']

Sample:
 conversation_id  start_message  end_message                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  message_count
           272.0              0            6 [CUSTOMER]: amazonのfireTVstickが見れない😢\n[AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET\n[CUSTOMER]: @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。\n[CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET\n[CUSTOMER]: @AmazonHelp こちらこそありがとうございました。\n[AMAZONHELP]: @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET              7
           272.0              6            6                                                                                                                                                                                                                                                                                                                                                                                                                                                              [AMAZONHELP]: @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET              1
           325.0              0            1                                                                                                                                                                                                                                                                                                                     [CUSTOMER]: amazonプライムビデオ、再生エラーが多いです\n[AMAZONHELP]: @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET              2

In [ ]:
# ============================================================
# STEP 6.4 — INSPECT LONG CONVERSATION
# ============================================================

long_conversation_chunks = conversation_chunks[
    conversation_chunks["conversation_id"] == 5159
]

print(
    "Conversation 5159 chunks:",
    len(long_conversation_chunks)
)

for i, (_, row) in enumerate(
    long_conversation_chunks.head(5).iterrows()
):

    print("\n" + "=" * 70)
    print("CHUNK", i)
    print("=" * 70)

    print(row["text"])

Conversation 5159 chunks: 75

======================================================================
CHUNK 0
======================================================================
[CUSTOMER]: Hit ❤ or re-tweet to get notified when the OnePlus 5T sale begins, exclusively on Amazon. Stay tuned to get #ANewView. https://t.co/0Ci7j8Lsoo
[CUSTOMER]: @115850 Im Waiting 😜
[CUSTOMER]: @140735 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 #amazonfestiveriddles@JeffBezos  @115850 @AmazonHelp
चोरो मुझे मेरे इन ऑडर के पैसे दो #AmazonGreatIndianFestivalSell बोलकर बेवकूफ बना रहे हो उपभोक्ताओं को
#Cashback मिलेगा बोलकर अब मुकर गए
कितनी ही बार तुमको ऑडर डिटेल भी सेंड कर दी है लिंक में देखो
https://t.co/o7HHLlYBJj
[CUSTOMER]: @115850 Can i get one for free please i am a regular customer
[CUSTOMER]: @115850 Got any job for me so that I can earn ₹33K to spend on 5T?
[CUSTOMER]: @115850 Where I find Diwali winner results
[CUSTOMER]: @115850 Redmi 4a 32gb stock me aaye tab बताना.

======================================================================
CHUNK 1
======================================================================
[CUSTOMER]: @115850 Where I find Diwali winner results
[CUSTOMER]: @115850 Redmi 4a 32gb stock me aaye tab बताना.
[CUSTOMER]: @284702 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 How much does it cost ?
[AMAZONHELP]: @140735 I'm afraid we do not have such option. However, you may take the advantage of the offers and deals from our website. ^HS
[CUSTOMER]: @AmazonHelp Ok
[AMAZONHELP]: @284286 Thanks for understanding. Wiish you the very best for the next sale.😉 ^RB
[AMAZONHELP]: @116925 I'm sorry for the inconvenience, please share your details here https://t.co/GIJyeYqKE0, we would look into this. Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ ^MD

======================================================================
CHUNK 2
======================================================================
[AMAZONHELP]: @284286 Thanks for understanding. Wiish you the very best for the next sale.😉 ^RB
[AMAZONHELP]: @116925 I'm sorry for the inconvenience, please share your details here https://t.co/GIJyeYqKE0, we would look into this. Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​ ^MD
[AMAZONHELP]: @284281 Well, if you're really interested, you might want to click here: https://t.co/NlW54e35cA :P Also, we're sure it's going to be worth the wait!^MD
[AMAZONHELP]: @284271 Could you please confirm which contest are you referring to so that we can assist you? ^GD
[AMAZONHELP]: @140735 Thanks for understanding, Jayant. ^KA
[AMAZONHELP]: @284268 Please click on notify by visiting this link: https://t.co/BCTx4FNxeC. You will be notified via email before the sale begins. Appreciate your interest. ^HS
[AMAZONHELP]: @284702 You may check the price here: https://t.co/h8Ob5KEh0y ^MN
[CUSTOMER]: @285585 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in

======================================================================
CHUNK 3
======================================================================
[AMAZONHELP]: @284702 You may check the price here: https://t.co/h8Ob5KEh0y ^MN
[CUSTOMER]: @285585 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @285432 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 Exchange available? One plus 5↔️ one plus 5T
[CUSTOMER]: @285444 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @285437 Thank you for your interest! You will be notified soon for the OnePlus 5T sale on Amazon.in
[CUSTOMER]: @115850 Is there any exchange program as I already have OnePlus 5.
[CUSTOMER]: @115850 Thank you @115850 😍😍😍

======================================================================
CHUNK 4
======================================================================
[CUSTOMER]: @115850 Is there any exchange program as I already have OnePlus 5.
[CUSTOMER]: @115850 Thank you @115850 😍😍😍
[CUSTOMER]: @115850 When I Get My Refund Email id - __email__
[CUSTOMER]: @115850 Is it flash sale then can I get op5T?
[AMAZONHELP]: @285444 You're welcome. Do keep us posted for any further concerns. ^SG
[AMAZONHELP]: @285437 I'm sure you'd like to upgrade your device to the OnePlus 5T, Sasi. Considering it has just released and is available only on preview sale, exchange for this device isn't currently available. ^JC
[CUSTOMER]: @AmazonHelp Thanks for letting me know.😍😍😘 Amazon
[AMAZONHELP]: @285432 I'd like to have a closer look at the refund issue. Please share your details in this link here: https://t.co/GIJyeYqKE0 and I'll reach out. Please don't provide your account details, we consider it to be personal information. Our page is visible to the public. ^KA

In [ ]:
# ============================================================
# STEP 7.1 — SUPPORT MESSAGE DISTRIBUTION
# ============================================================

print("=" * 70)
print("INBOUND / OUTBOUND DISTRIBUTION")
print("=" * 70)

print(amazon_clean["inbound"].value_counts())

print("\nPercentage:")
print(
    amazon_clean["inbound"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nExample rows:")
print(
    amazon_clean[
        ["conversation_id", "tweet_id", "inbound", "text"]
    ].head(10).to_string(index=False)
)

======================================================================
INBOUND / OUTBOUND DISTRIBUTION
======================================================================
inbound
True     203598
False    170444
Name: count, dtype: int64

Percentage:
inbound
True     54.43
False    45.57
Name: proportion, dtype: float64

Example rows:
 conversation_id  tweet_id  inbound                                                                                                                                                      text
           272.0       272     True                                                                                                                                  amazonのfireTVstickが見れない😢
           272.0       269    False                            @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET
           272.0       270     True                                                                                                             @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。
           272.0       271     True                                                                                          @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。
           272.0       273    False                                                                                     @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET
           272.0       274     True                                                                                                                             @AmazonHelp こちらこそありがとうございました。
           272.0       275    False                                                                                                    @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET
           325.0       325     True                                                                                                                                  amazonプライムビデオ、再生エラーが多いです
           325.0       324    False @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET
           617.0       617     True                                                                                     Way to drop the ball on customer service @115821 so pissed right now!

In [ ]:
# ============================================================
# STEP 7.2 — FIND CONVERSATIONS WITH BOTH SIDES
# ============================================================

conversation_stats = (
    amazon_clean
    .groupby("conversation_id")
    .agg(
        message_count=("tweet_id", "count"),
        inbound_count=("inbound", "sum"),
        outbound_count=("inbound", lambda x: (~x).sum())
    )
    .reset_index()
)

conversation_stats["has_customer"] = (
    conversation_stats["inbound_count"] > 0
)

conversation_stats["has_amazonhelp"] = (
    conversation_stats["outbound_count"] > 0
)

support_conversations = conversation_stats[
    conversation_stats["has_customer"]
    & conversation_stats["has_amazonhelp"]
].copy()

print("=" * 70)
print("SUPPORT CONVERSATION ANALYSIS")
print("=" * 70)

print(
    "Total conversations:",
    len(conversation_stats)
)

print(
    "Conversations with customer + AmazonHelp:",
    len(support_conversations)
)

print(
    "Conversations with customer only:",
    (
        conversation_stats["has_customer"]
        & ~conversation_stats["has_amazonhelp"]
    ).sum()
)

print(
    "Conversations with AmazonHelp only:",
    (
        ~conversation_stats["has_customer"]
        & conversation_stats["has_amazonhelp"]
    ).sum()
)

======================================================================
SUPPORT CONVERSATION ANALYSIS
======================================================================
Total conversations: 82534
Conversations with customer + AmazonHelp: 82534
Conversations with customer only: 0
Conversations with AmazonHelp only: 0

In [ ]:
# ============================================================
# STEP 7.3 — INSPECT A REAL SUPPORT CONVERSATION
# ============================================================

short_support = support_conversations[
    support_conversations["message_count"].between(2, 10)
]

print(
    "Short support conversations:",
    len(short_support)
)

if len(short_support) > 0:

    support_id = short_support.iloc[0]["conversation_id"]

    example_support = (
        amazon_clean[
            amazon_clean["conversation_id"] == support_id
        ]
        .sort_values("created_at")
    )

    print("\nConversation ID:", support_id)
    print("Messages:", len(example_support))

    print("\n" + "=" * 70)

    for _, row in example_support.iterrows():

        speaker = (
            "CUSTOMER"
            if row["inbound"]
            else "AMAZONHELP"
        )

        print(f"\n[{speaker}]")
        print(str(row["text"]).strip())

Short support conversations: 77925

Conversation ID: 272.0
Messages: 7

======================================================================

[CUSTOMER]
amazonのfireTVstickが見れない😢

[AMAZONHELP]
@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET

[CUSTOMER]
@AmazonHelp ありがとうございます。
今、電話で主人が対応していただいてます。

[CUSTOMER]
@AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。

[AMAZONHELP]
@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET

[CUSTOMER]
@AmazonHelp こちらこそありがとうございました。

[AMAZONHELP]
@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

In [ ]:
# ============================================================
# STEP 8.1 — BUILD SUPPORT CASES
# ============================================================

def build_support_cases(df, context_messages=3):
    """
    Build retrieval documents around AmazonHelp responses.

    Each case contains:
      - recent customer/support context
      - the AmazonHelp response
      - conversation metadata
    """

    df = df.copy()

    # Make sure chronological order is correct
    df = df.sort_values(
        ["conversation_id", "created_at"]
    )

    cases = []

    for conversation_id, group in df.groupby(
        "conversation_id",
        sort=False
    ):

        group = group.reset_index(drop=True)

        for i, row in group.iterrows():

            # We only create a retrieval case when
            # AmazonHelp is responding.
            if bool(row["inbound"]):
                continue

            # Need at least one previous message
            if i == 0:
                continue

            start = max(0, i - context_messages)

            context = group.iloc[start:i + 1]

            messages = []

            for _, msg in context.iterrows():

                speaker = (
                    "CUSTOMER"
                    if bool(msg["inbound"])
                    else "AMAZONHELP"
                )

                text = str(msg["text"]).strip()

                if not text:
                    continue

                messages.append(
                    f"[{speaker}]: {text}"
                )

            if not messages:
                continue

            cases.append({
                "conversation_id": conversation_id,
                "response_tweet_id": row["tweet_id"],
                "created_at": row["created_at"],
                "text": "\n".join(messages),
                "response": str(row["text"]).strip(),
                "message_count": len(messages)
            })

    return pd.DataFrame(cases)


support_cases = build_support_cases(
    amazon_clean,
    context_messages=3
)

print("=" * 70)
print("SUPPORT CASE CORPUS")
print("=" * 70)

print("Total support cases:", len(support_cases))

print("\nColumns:")
print(support_cases.columns.tolist())

print("\nMissing values:")
print(support_cases.isnull().sum())

print("\nSample:")
print(
    support_cases.head(3)
    .to_string(index=False)
)

======================================================================
SUPPORT CASE CORPUS
======================================================================
Total support cases: 169430

Columns:
['conversation_id', 'response_tweet_id', 'created_at', 'text', 'response', 'message_count']

Missing values:
conversation_id      0
response_tweet_id    0
created_at           0
text                 0
response             0
message_count        0
dtype: int64

Sample:
 conversation_id  response_tweet_id                created_at                                                                                                                                                                                                                                                                                                                                                                       text                                                                                                                       response  message_count
           272.0                269 2017-11-22 09:23:01+00:00                                                                                                                                                                                         [CUSTOMER]: amazonのfireTVstickが見れない😢\n[AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET              2
           272.0                273 2017-11-22 09:40:27+00:00 [AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET\n[CUSTOMER]: @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。\n[CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET                                                          @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET              4
           272.0                275 2017-11-22 10:06:26+00:00                                                                                         [CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET\n[CUSTOMER]: @AmazonHelp こちらこそありがとうございました。\n[AMAZONHELP]: @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET                                                                         @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET              4

In [95]:
print("support_cases exists:", "support_cases" in globals())

if "support_cases" in globals():
    print("Rows:", len(support_cases))
    print("Columns:", support_cases.columns.tolist())

support_cases exists: False

In [ ]:
print(type(support_cases))
print(len(support_cases))
print(support_cases.columns.tolist())

<class 'pandas.DataFrame'>
169430
['conversation_id', 'response_tweet_id', 'created_at', 'text', 'response', 'message_count']

In [96]:
import pandas as pd

print("DataFrames containing 169,430 rows:\n")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame) and len(obj) == 169430:
        print("VARIABLE:", name)
        print("COLUMNS:", obj.columns.tolist())
        print()

DataFrames containing 169,430 rows:

In [97]:
import pandas as pd

print("Current DataFrames:\n")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"{name:30} rows={len(obj):,}")

Current DataFrames:

__                             rows=4
___                            rows=3
df_sample                      rows=1,000
_2                             rows=10
_4                             rows=20
chunk                          rows=11,774
brand_tweets                   rows=5,025
customer_rows                  rows=6,749
brand_rows                     rows=1,817
brand_rows_for_brand           rows=191
selected                       rows=893
amazon_df                      rows=270,344
amazon_examples                rows=20
matches                        rows=0
_11                            rows=20
conversation                   rows=3
_12                            rows=3
parent_df                      rows=2,811,774
conversation_lengths           rows=82,534
customer_reply_ids             rows=750,497
all_tweets                     rows=2,811,774
amazon_conversations           rows=374,042
brand_df                       rows=43,265
comparison_df                  rows=4
_41                            rows=4
amazon_tweet_map               rows=374,042
part                           rows=1,434
amazon_clean                   rows=374,042
_47                            rows=5
intent_sample                  rows=4,874
customer_messages              rows=203,598
intent_examples                rows=200
keyword_df                     rows=23
_60                            rows=23
delivery_examples              rows=43
refund_examples                rows=15
prime_examples                 rows=14
intent_keyword_df              rows=9
_67                            rows=9
first_customer_messages        rows=82,534
candidates                     rows=82,509
golden_set                     rows=200
golden_conversations           rows=1,691
_81                            rows=10
_83                            rows=20
_90                            rows=20
_91                            rows=3

In [ ]:
# ============================================================
# STEP 8.2 — INSPECT SUPPORT CASES
# ============================================================

for i, row in support_cases.head(5).iterrows():

    print("\n" + "=" * 70)
    print(f"SUPPORT CASE {i}")
    print("=" * 70)

    print("Conversation ID:", row["conversation_id"])
    print("Response Tweet:", row["response_tweet_id"])

    print("\nCASE:")
    print(row["text"])

======================================================================
SUPPORT CASE 0
======================================================================
Conversation ID: 272.0
Response Tweet: 269

CASE:
[CUSTOMER]: amazonのfireTVstickが見れない😢
[AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET

======================================================================
SUPPORT CASE 1
======================================================================
Conversation ID: 272.0
Response Tweet: 273

CASE:
[AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET
[CUSTOMER]: @AmazonHelp ありがとうございます。
今、電話で主人が対応していただいてます。
[CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET

======================================================================
SUPPORT CASE 2
======================================================================
Conversation ID: 272.0
Response Tweet: 275

CASE:
[CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET
[CUSTOMER]: @AmazonHelp こちらこそありがとうございました。
[AMAZONHELP]: @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

======================================================================
SUPPORT CASE 3
======================================================================
Conversation ID: 325.0
Response Tweet: 324

CASE:
[CUSTOMER]: amazonプライムビデオ、再生エラーが多いです
[AMAZONHELP]: @115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET

======================================================================
SUPPORT CASE 4
======================================================================
Conversation ID: 617.0
Response Tweet: 615

CASE:
[CUSTOMER]: Way to drop the ball on customer service @115821 so pissed right now!
[AMAZONHELP]: @115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN

In [ ]:
# ============================================================
# STEP 8.3 — CORPUS STATISTICS
# ============================================================

print("=" * 70)
print("CORPUS STATISTICS")
print("=" * 70)

print("Support cases:", len(support_cases))

print(
    "Unique conversations:",
    support_cases["conversation_id"].nunique()
)

print(
    "Unique AmazonHelp responses:",
    support_cases["response_tweet_id"].nunique()
)

print("\nMessages per case:")
print(
    support_cases["message_count"]
    .describe()
)

print("\nCase length:")
support_cases["text_length"] = (
    support_cases["text"]
    .str.len()
)

print(
    support_cases["text_length"]
    .describe()
)

======================================================================
CORPUS STATISTICS
======================================================================
Support cases: 169430
Unique conversations: 82534
Unique AmazonHelp responses: 169430

Messages per case:
count    169430.000000
mean          3.029098
std           0.964407
min           2.000000
25%           2.000000
50%           3.000000
75%           4.000000
max           4.000000
Name: message_count, dtype: float64

Case length:
count    169430.00000
mean        405.98335
std         165.12301
min          51.00000
25%         277.00000
50%         389.00000
75%         509.00000
max        1193.00000
Name: text_length, dtype: float64

In [ ]:
# ============================================================
# STEP 8.4 — DEDUPLICATION
# ============================================================

before = len(support_cases)

support_cases = (
    support_cases
    .drop_duplicates(subset=["text"])
    .reset_index(drop=True)
)

after = len(support_cases)

print("Before deduplication:", before)
print("After deduplication: ", after)
print("Duplicates removed:  ", before - after)

Before deduplication: 169430
After deduplication:  169430
Duplicates removed:   0

In [ ]:
# ============================================================
# STEP 8.5 — LIGHT TEXT NORMALIZATION
# ============================================================

import re

def normalize_text(text):
    text = str(text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text)

    # Remove excessive repeated punctuation
    text = re.sub(r"([!?.,])\1{3,}", r"\1\1", text)

    return text.strip()


support_cases["text_normalized"] = (
    support_cases["text"]
    .apply(normalize_text)
)

print(
    support_cases[
        ["text", "text_normalized"]
    ].head(3).to_string(index=False)
)

                                                                                                                                                                                                                                                                                                                                                                      text                                                                                                                                                                                                                                                                                                                                                       text_normalized
                                                                                                                                                                                        [CUSTOMER]: amazonのfireTVstickが見れない😢\n[AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET                                                                                                                                                                                     [CUSTOMER]: amazonのfireTVstickが見れない😢 [AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET
[AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET\n[CUSTOMER]: @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。\n[CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET [AMAZONHELP]: @115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET [CUSTOMER]: @AmazonHelp ありがとうございます。 今、電話で主人が対応していただいてます。 [CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。 保証期間も過ぎてるので買い直しになるんでしょうね。 [AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET
                                                                                        [CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。\n[AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET\n[CUSTOMER]: @AmazonHelp こちらこそありがとうございました。\n[AMAZONHELP]: @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET                                                                                        [CUSTOMER]: @AmazonHelp 電話で対応してもらいましたが改良されませんでした。 保証期間も過ぎてるので買い直しになるんでしょうね。 [AMAZONHELP]: @115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET [CUSTOMER]: @AmazonHelp こちらこそありがとうございました。 [AMAZONHELP]: @115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET

In [ ]:
# ============================================================
# STEP 8.6 — GOLDEN SET PROTECTION
# ============================================================

golden_conversation_ids = set(
    golden_raw["conversation_id"]
    .astype("int64")
    .tolist()
)

corpus_conversation_ids = set(
    support_cases["conversation_id"]
    .astype("int64")
    .tolist()
)

overlap = (
    golden_conversation_ids
    & corpus_conversation_ids
)

print("=" * 70)
print("GOLDEN SET OVERLAP")
print("=" * 70)

print("Golden conversations:", len(golden_conversation_ids))
print("Corpus conversations:", len(corpus_conversation_ids))
print("Overlap:", len(overlap))

======================================================================
GOLDEN SET OVERLAP
======================================================================
Golden conversations: 200
Corpus conversations: 82534
Overlap: 200

In [ ]:
retrieval_corpus = support_cases[
    ~support_cases["conversation_id"]
    .astype("int64")
    .isin(golden_conversation_ids)
].copy()

retrieval_corpus = retrieval_corpus.reset_index(drop=True)

print("Full support cases:", len(support_cases))
print("Golden conversations:", len(golden_conversation_ids))
print("Retrieval corpus:", len(retrieval_corpus))

Full support cases: 169430
Golden conversations: 200
Retrieval corpus: 168680

In [98]:
import pandas as pd

# Show DataFrames that are likely to be support-case related
for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        columns = set(obj.columns)

        if (
            "conversation_id" in columns
            and "tweet_id" in columns
            and len(obj) > 100000
        ):
            print("=" * 70)
            print("VARIABLE:", name)
            print("ROWS:", len(obj))
            print("COLUMNS:", obj.columns.tolist())

======================================================================
VARIABLE: all_tweets
ROWS: 2811774
COLUMNS: ['tweet_id', 'in_response_to_tweet_id', 'conversation_id']
======================================================================
VARIABLE: amazon_conversations
ROWS: 374042
COLUMNS: ['tweet_id', 'in_response_to_tweet_id', 'conversation_id']
======================================================================
VARIABLE: amazon_tweet_map
ROWS: 374042
COLUMNS: ['tweet_id', 'conversation_id']
======================================================================
VARIABLE: amazon_clean
ROWS: 374042
COLUMNS: ['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
======================================================================
VARIABLE: customer_messages
ROWS: 203598
COLUMNS: ['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']

In [99]:
print("Variables related to support cases:")

for name in list(globals().keys()):
    if any(word in name.lower() for word in ["support", "case", "reply", "message"]):
        obj = globals()[name]
        
        if hasattr(obj, "shape"):
            print(f"{name:30} shape={obj.shape}")

Variables related to support cases:
customer_reply_ids             shape=(750497, 2)
total_message_lengths          shape=(82534,)
customer_messages              shape=(203598, 8)
first_customer_messages        shape=(82534, 10)

In [100]:
print("FIRST CUSTOMER MESSAGES")
print(first_customer_messages.columns.tolist())
print(first_customer_messages.head(3).to_string())

print("\n" + "=" * 80)

print("CUSTOMER MESSAGES")
print(customer_messages.columns.tolist())
print(customer_messages.head(3).to_string())

FIRST CUSTOMER MESSAGES
['conversation_id', 'tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'message_length', 'conversation_length']
   conversation_id  tweet_id author_id  inbound                created_at                                                                   text response_tweet_id  in_response_to_tweet_id  message_length  conversation_length
0            272.0       272    115770     True 2017-11-22 09:14:39+00:00                                               amazonのfireTVstickが見れない😢               269                    269.0              24                    7
1            325.0       325    115792     True 2017-11-22 08:55:35+00:00                                               amazonプライムビデオ、再生エラーが多いです               324                      NaN              24                    2
2            617.0       617    115820     True 2017-10-31 22:16:32+00:00  Way to drop the ball on customer service @115821 so pissed right now!               615                    615.0              69                    5

================================================================================
CUSTOMER MESSAGES
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']
   tweet_id author_id  inbound                created_at                                                              text response_tweet_id  in_response_to_tweet_id  conversation_id
0       272    115770     True 2017-11-22 09:14:39+00:00                                          amazonのfireTVstickが見れない😢               269                      NaN            272.0
2       270    115770     True 2017-11-22 09:24:30+00:00                     @AmazonHelp ありがとうございます。\n今、電話で主人が対応していただいてます。               NaN                    269.0            272.0
3       271    115770     True 2017-11-22 09:30:36+00:00  @AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。               273                    269.0            272.0

In [101]:
print("Customer messages:", len(customer_messages))

print("\nresponse_tweet_id:")
print(customer_messages["response_tweet_id"].notna().sum(), "not null")
print(customer_messages["response_tweet_id"].isna().sum(), "null")

print("\nUnique response_tweet_id:")
print(customer_messages["response_tweet_id"].dropna().nunique())

print("\nUnique conversation IDs:")
print(customer_messages["conversation_id"].nunique() if "conversation_id" in customer_messages.columns else "conversation_id not present")

Customer messages: 203598

response_tweet_id:
168466 not null
35132 null

Unique response_tweet_id:
168466

Unique conversation IDs:
82534

In [102]:
support_cases = customer_messages[
    customer_messages["response_tweet_id"].notna()
].copy()

In [103]:
print(len(support_cases))

168466

In [104]:
print("amazon_clean columns:")
print(amazon_clean.columns.tolist())

print("\ncustomer_messages columns:")
print(customer_messages.columns.tolist())

amazon_clean columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']

customer_messages columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'conversation_id']

In [105]:
print("\nAmazon clean rows:", len(amazon_clean))
print("Customer messages:", len(customer_messages))

print("\nCustomer messages with response:", 
      customer_messages["response_tweet_id"].notna().sum())

print("\nAmazon clean unique tweet IDs:",
      amazon_clean["tweet_id"].nunique())

Amazon clean rows: 374042
Customer messages: 203598

Customer messages with response: 168466

Amazon clean unique tweet IDs: 374042